### ISSUE TITLE
Available options/default value for trailingSemicolon

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#10]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
None, do we need an option to allow missing semicolons on the last property?

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
I think we should allow that because that might be a code-style in an environment where people don't use minifiers?

**Comment by CITguy** [comment]
Missing semicolon is bad practice. I vote the rule default to `enabled`.

**Comment by kokarn** [comment]
I agree that missing semicolon should be a warning as default, but i'd like to have the option to allow skipping it on the last property.

**Comment by jwilsson** [comment]
I'm going to mark this as complete over in #67 since we all seem to agree that it should be enabled and we can always add options later.

**Comment by kokarn** [comment]
Sounds good to me :+1:

**Comment by CITguy** [comment]
:+1:

**Comment by shellscape** [comment]
Close issue?

**Comment by kokarn** [comment]
Yeah, agreed
