### ISSUE TITLE
Linter plugin support

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#101]
I was thinking about some sort of plugin support. That users of `lesshint` can create their own linters which doesn't necessarily belong in core (company specific linters or whatever) but still want to use the infrastructure provided by `lesshint` to lint their code.

We already got most of the structure in place for this in `linter.js`. What we need to do is basically this (probably forgot something):
* Merge our current list of linters with a `plugins` array from `.lesshintrc`.
* Write some docs on what a linter needs to do. Expose a `lint` method, return an array etc.

**Comment by kokarn** [comment]
+1

**Comment by shellscape** [comment]
Also would recommend configuration outside of .lesshintrc

**Comment by jwilsson** [comment]
@shellscape do you mean via Gulp plugins for instance?

**Comment by shellscape** [comment]
via:

```javascript
lesshint.configure({ plugins: [...] });
```

or some such

**Comment by jwilsson** [comment]
:+1:

**Comment by JoshuaKGoldberg** [comment]
+1 as per #195. @jwilsson how much documentation on the linter is left to do?

**Comment by jwilsson** [comment]
@JoshuaKGoldberg The things we need to document are:
* The things each linter should expose,
    * `name` - Name of the linter.
    * `nodeTypes ` - Array of the accepted node types which will be passed to it.
    * `lint` - The method that will be called with `config` (options for this rule) and `node`.
    * `message` - Not currently used but might be at some point, would probably make sense to expose it just for consistency. Could be marked as optional.
* What it should return,
    * Array of linter results (as shown here: https://github.com/lesshint/lesshint#writing-your-own-reporter). All properties will be set by `lesshint` but can be overridden by each linter. The ones that always makes sense to override are `column`, `line`, and `message`.
    * `undefined` if no errors or nothing to check.

Other things that would be nice to document is a link to the docs for `postcss`, `postcss-less`, `postcss-selector-parser`, and `postcss-values-parser` since they are of great help.

Another thing I thought about is a CLI flag, `-p`/`--plugins` perhaps?

**Comment by JoshuaKGoldberg** [comment]
Is `plugins` the right name for this? In the future you might want to allow for other type of extensions.

Since `linter.js` lists the default linters under the variable `linters`, I propose this be in JSON:

```json
"linterDirectories": [ "path/to/linters", "path/to/more/linters"]
```
