### ISSUE TITLE
Replace JSHint/JSCS with ESLint

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#102]
I've recently been working more and more with ESLint and I really like it. It also seems unnecessary to include two tools when one would suffice. Does anyone have any objections to this? Otherwise, I'll just do it :wink:

**Comment by kokarn** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0

**Comment by shellscape** [comment]
I've got no objections

**Comment by jwilsson** [comment]
Closed by 68e1b3ed9a35e59dddde43709e862be41af380f1.
