### ISSUE TITLE
[feature request] validate selector naming convention

### ISSUE THREAD

**Issue by AoDev** [lesshint/lesshint#105]
Hello, 

I'd like to be able to validate selector naming.

Until now I have always been with people following the convention to use dashes / lowercase names but a coworker has been using camel case in his previous workplace. 

`btn-primary` vs `btnPrimary` 

Maybe a simple `lowercase` test is enough ?

At first I could see settings for:
* underscore (true | false)
* dash (true | false)
* case ('lowercase' | 'mixed')

**Comment by kokarn** [comment]
This sounds insanely useful actually.

+1 from me

**Comment by jwilsson** [comment]
I agree, sounds awesome.

@AoDev interested in a PR?

**Comment by shellscape** [comment]
various common cases:

* sausage
* snake
* camel
* lower
* upper

**Comment by AoDev** [comment]
@jwilsson I'll check the code to see how "hard" it is to prepare a PR. I am fighting multiple fronts and another just slows everything :P

**Comment by AoDev** [comment]
@jwilsson I have started with it.
