### ISSUE TITLE
[bug?] nesting defeats qualifyingElement rule

### ISSUE THREAD

**Issue by AoDev** [lesshint/lesshint#106]
Hello,

I just realised that:

`.navbar a.active` will trigger the qualifyingElement error.

but if I nest it:

```css
.navbar {
  a {
    &.active {
      
    }
  }
}
```

the error will be "solved".

Maybe it's a hard one. Whether it can be solved or not, a warning in the docs would be a nice thing to do.
And it's possible that more rules behave in the same way.

**Comment by jwilsson** [comment]
Hi,
I don't think it will be especially hard to check for but I'm just wondering if a option to enable/disable the check on parent selectors would make any sense?

**Comment by AoDev** [comment]
I think that it should be coherent. If this rule is to prevent someone from writing:

```
a.active
```
it should not matter whether one is using, less, sass, stylus, etc. It's not about code style but avoiding bloated useless selectors, isn't it? Personally I would not add such option.

On the other hand, I do have problems with this rules because when I want to override some styles from a framework like bootstrap where there are such styles `a.active`, I'd like to be able to add an exception. (but that's another issue)

**Comment by jwilsson** [comment]
Alright, lets add a check for parent selectors too. Do you wanna submit a PR @AoDev? Otherwise I'll take care of it.
