### ISSUE TITLE
Available options/default value for emptyRule

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#11]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
None, do we need any options or is it enough with `enabled: true/false`?

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
Right now it's allowed to have empty blocks with comments in them, eg 
```
div {
// this will be valid
}
```

Maybe an option to disallow them as well?

**Comment by CITguy** [comment]
An empty block containing only comments is still an empty block. I vote it default to `enabled`.

**Comment by kokarn** [comment]
At the moment lesshint doesn't count empty blocks with comments as empty. 

I actually quite like this because that way you can have something that validates but still contains a suggested styling block or similar.

Might be something we could fix when we implement #55 but that would be quite a bit uglier imo.

**Comment by jwilsson** [comment]
I agree with @kokarn, it's quite nice to add a dummy comment to blocks which you want empty for clarity. I find it quite nice to be able to do things like this for example:

```css
@keyframes scale {
    0% {
        // Empty
    }
    
    100% {
        transform: scale(1);
    }
}
```

**Comment by kokarn** [comment]
Unless @CITguy has some objections we can close this in #67 and add that option later

**Comment by CITguy** [comment]
:+1:

**Comment by kokarn** [comment]
Great! Closing this then :) (Yeah, i'm slow sometimes)
