### ISSUE TITLE
excludedFiles (in the config file) isn't working

### ISSUE THREAD

**Issue by cageygee3** [lesshint/lesshint#113]
In my config file, I have two files I'm trying to exclude:

```
$ cat .lesshintrc
{
  "excludedFiles": [
    "elements.less",
    "flex.less"
  ],
  "idSelector": {
    "enabled": false
  },
  "qualifyingElement": {
    "allowWithClass": true
  },
  "zeroUnit": {
    "style": "no_unit"
  }
}
```

But when I run lesshint on my stylesheets directory, the files are included:

```
$ ./node_modules/lesshint/bin/lesshint src/css/
elements.less: line 23, col 1, parse error: Please check validity of the block starting from line #23
events.less: line 84, col 3, propertyOrdering: Property ordering is not alphabetized
flex.less: line 17, col 1, parse error: Please check validity of the block starting from line #17
styles.less: line 130, col 3, propertyOrdering: Property ordering is not alphabetized
timeline.less: line 22, col 5, duplicateProperty: Duplicate property: "cursor".
```

Likewise, trying to exclude multiple files on the command-line doesn't work:

```
$ ./node_modules/lesshint/bin/lesshint src/css/ -e '(elements|flex).less'
elements.less: line 23, col 1, parse error: Please check validity of the block starting from line #23
events.less: line 84, col 3, propertyOrdering: Property ordering is not alphabetized
flex.less: line 17, col 1, parse error: Please check validity of the block starting from line #17
styles.less: line 130, col 3, propertyOrdering: Property ordering is not alphabetized
timeline.less: line 22, col 5, duplicateProperty: Duplicate property: "cursor".
```

The only thing I can get working is excluding a single file on the command line:

```
$ ./node_modules/lesshint/bin/lesshint src/css/ -e elements.less
events.less: line 84, col 3, propertyOrdering: Property ordering is not alphabetized
flex.less: line 17, col 1, parse error: Please check validity of the block starting from line #17
styles.less: line 130, col 3, propertyOrdering: Property ordering is not alphabetized
timeline.less: line 22, col 5, duplicateProperty: Duplicate property: "cursor".
```

Any idea what's going on?

**Comment by jwilsson** [comment]
Hmm, that sounds really weird. Are you interested in taking a look?

**Comment by cageygee3** [comment]
Sure, I'll poke around and see what I can dig up.

**Comment by cageygee3** [comment]
I have a fix for this (very simple), but I'll need some help getting my tests passing before I can submit a pull request. See #114.

**Comment by cageygee3** [comment]
I was able to get my tests passing by commenting out the eslint rule that requires LF only, so I should be able to submit a pull request (with tests!) this evening. :smile:

**Comment by kokarn** [comment]
Great work! Happy that there are more people contributing and helping out.

**Comment by cageygee3** [comment]
Since it'll probably be a while before the ignore-this-line functionality is ready to go (issue #55), would it be possible to get a new release with this fix?

**Comment by jwilsson** [comment]
@cageygee3 I'm just finishing up some last things for a `1.3.0` release which should be up Friday morning (CET).

**Comment by cageygee3** [comment]
Awesome, sounds great, thanks!

**Comment by jwilsson** [comment]
And `1.3.0` is published to npm!

**Comment by cageygee3** [comment]
Great, thanks! :smile:
