### ISSUE TITLE
SpaceAroundOperator crashes linting execution.

### ISSUE THREAD

**Issue by miloszsobczak** [lesshint/lesshint#120]
Actually, we're not sure if it's problem of lesshint itself or gulp-less plugin, but the throws comes from lesshint plugin.

```
Plumber found unhandled error:
 Error in plugin 'gulp-lesshint'
Message:
    TypeError: Cannot read property 'content' of undefined
    at Node.<anonymous> (/var/www/symfony/node_modules/gulp-lesshint/node_modules/lesshint/lib/linters/space_around_operator.js:32:63)
```

It's kinda annoying because we need to disable _SpaceAroundOperator_ checking to get thinkgs work.

**Comment by jwilsson** [comment]
Confirmed, it's a bug in `lesshint`. We don't check the variable values (we always assume it's a object but it could be null). 

@miloszsobczak Are you willing to take a stab at it?

**Comment by miloszsobczak** [comment]
@jwilsson thanks for confirmation. I will fix it later on and make pull request.

**Comment by jwilsson** [comment]
@miloszsobczak Awesome, looking forward to it!
