### ISSUE TITLE
Is there a way to exclude/escape/disable something for a single line?

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/lesshint#128]
I didn't see this in the docs, sorry if I just missed it. What if I have to use a certain thing on one line because of an edge but don't want it anywhere else? Can I put a comments on the line above and the line below to allow it? Or something like that.

**Comment by jwilsson** [comment]
Not at this moment, we're discussing it in #55. I don't think anyone's working on it though. If you're interested, give it a shout over there!
