### ISSUE TITLE
Available options/default value for idSelector

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#13]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
None, do we need any options or is it enough with enabled: true/false?

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
A list of allowed overrides would be nice i think because then you can use them as a namespace until we get shadow-dom.

Say you are going to implement code from Example Corp on MyPage. 
Wrapping everything in a block with ```#example-corp``` is a pretty smooth way to namespace everything.

**Comment by jwilsson** [comment]
I'm thinking we could do this in the same way as we discussed in [#14](https://github.com/jwilsson/lesshint/issues/14#issuecomment-98672980) with inline comments.

**Comment by kokarn** [comment]
Not sure I like that for this particular option, would be much cleaner with a syntax like that of the [JSHint](https://github.com/gruntjs/grunt-contrib-jshint) globals.

**Comment by jwilsson** [comment]
Hmm, perhaps both are needed? Both an exclude/ignore/whatever option and the ability to exclude certain lines/cases with comments.

**Comment by kokarn** [comment]
Yeah, that makes sense

**Comment by kokarn** [comment]
Allowed selectors are implemented already and the inline option don't really make sense any more. Closing.

**Comment by deanc** [comment]
Sorry to resurrect this from the dead @jwilsson 

I'd argue this is quite an opinionated, although technically not incorrect approach. Could we have an option to disable this rule entirely? There are some codebases one might inherit where it's not possible to target the DOM elements without an ID effectively. A simple option to set this to `false` would suffice :)

**Comment by jwilsson** [comment]
@deanc You can disable any rule by setting it to `false`, perhaps it's a bit unclear in the docs.
