### ISSUE TITLE
spaceBetweenParents isn't multi-line friendly

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/lesshint#130]
This fails:

```less
.button-base(
  @baseBackgroundColour,
  @focusBackgroundColor: @baseBackgroundColour,
  @hoverBackgroundColour: lighten(@baseBackgroundColour, @buttonBackgroundDelta),
  @activeBackgroundColour: darken(@baseBackgroundColour, @buttonBackgroundDelta)
) {
  // ...
}
```

**Comment by adam-lynch** [comment]
Actually, a few things are like this. `spaceAroundComma` fails on the second line there :/

**Comment by jwilsson** [comment]
Yeah, kind of the same issue as `spaceAroundComma` in #119. We need some way (a setting, just ignoring it, something else) to check for new lines before/after commas and parentheses. 

What are people's thoughts on this?
