### ISSUE TITLE
Checking trailingWhitespace outputs unexpected syntax Error.

### ISSUE THREAD

**Issue by miloszsobczak** [lesshint/lesshint#134]
When I lesshit my code with usage of trailingWhitespace feature, lesshint logs weird syntax Error.
`Syntax "undefined" is not supported yet, sorry`

It's visible even in tests:
```
lesshint
    #trailingWhitespace()
      ✓ should allow lines with no trailing whitespace
      ✓ should allow lines with trailing new line characters
      ✓ should not allow lines with trailing whitespace
      ✓ should not allow lines with trailing tabs
Syntax "undefined" is not supported yet, sorry
      ✓ should ignore empty files
```

I you confirm it as bug, let me send u pull request with some fixes.

**Comment by jwilsson** [comment]
It seems like it's related to empty files (since it's logged on that test and I was able to trigger the error myself with a empty file), I guess we should just skip empty files and never send them to `gonzales-pe`.

**Comment by miloszsobczak** [comment]
It could be what you mentioned. Let me handle this.
