### ISSUE TITLE
importPath for .css file

### ISSUE THREAD

**Issue by wareczek** [lesshint/lesshint#140]
`@import (inline) "path/to/file.css";`

throws error:
> Warning: main.less: line 1, col 18, importPath: Imported file, "path/to/file.css" should not include the file extension.

But omitting file extension is only availbe for "*.less" files.

http://lesscss.org/features/#import-directives-feature-file-extensions
> If it does not have an extension, .less will be appended and it will be included as a imported Less file.

**Comment by jwilsson** [comment]
I guess we should add a check to see if the file extension is `.less` and only report it then. @wareczek do you wanna fix it?
