### ISSUE TITLE
Move stylish reporter to its own package

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#147]
Just to make sure we don't forget our discussion in #146.

The `stylish` reporter should be moved to its own repo and package. What we need to do right now:
- [x]  Move files to the new repo.
- [x]  Remove the `chalk` dependency from `package.json`.
- [x]  Add a special case for `stylish` when we load reporters so it'll still work with the old name (since the new one will be `lesshint-reporter-stylish` or similar).
- [x]  Add deprecation notice when trying to use `stylish` with the old name.
- [x]  Some minor doc updates.
- [x] Add a general `getReporter()` method to allow other packages to use our loading logic.

EDIT:
Added `getReporter()` point.

**Comment by shellscape** [comment]
There should be a minimalist core reporter in the event that no reporters are specified. Or were you planning on making the stylish reporter a dependency of lesshint?

**Comment by jwilsson** [comment]
@shellscape Yes, exactly. We move it to its own package and add it as a dependency here.
