### ISSUE TITLE
Max Warnings Configuration

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#149]
Do we have a max warnings configuration I'm not seeing? Wiring this up to gulp (through gulp-lesshint) I'm trying to force gulp to exit with 1 if there's any warnings at all. Certainly something I could add to the gulp plugin, but was thinking that lesshint itself should return 1 through the cli and something falsey if used programmatically. Thoughts?

**Comment by jwilsson** [comment]
Absolutely, sounds great!

**Comment by jwilsson** [comment]
@shellscape Do you wanna do it or should we mark it as "Help wanted"?

**Comment by shellscape** [comment]
was just thinking about this today. I can take care of it, but probably won't be until next week sometime. busy weekend ahead!
