### ISSUE TITLE
New option for "spaceAfterPropertyColon" linter

### ISSUE THREAD

**Issue by BiggestBuccaneer** [lesshint/lesshint#154]
Can we have "at_least_one_space" option for "spaceAfterPropertyColon" linter? Thats allows to align equal values  of related properties. Like so:
```
.foo {
    width:  20px;
    height: 20px;
}
```
I can create PR

**Comment by idelpivnitskiy** [comment]
@BiggestBuccaneer looks great to me! :+1:

**Comment by jwilsson** [comment]
Sounds good to me, PR welcome :)
