### ISSUE TITLE
Fail on Warning

### ISSUE THREAD

**Issue by red2678** [lesshint/lesshint#163]
Hi,

I am trying to get my gulp task to fail with exit code 1. According to the docs, it should if one or more linting errors with a severity of warning were found, however, I always seem to get `0`

This is my task:
```javascript
gulp.task('lintLess', function() {
  return gulp.src(paths.less)
      .pipe(lesshint())
      .pipe(lesshint.reporter());
});
```

Results screen shot:
![image](https://cloud.githubusercontent.com/assets/1896036/14029345/c5a97b6e-f1be-11e5-973f-9d37c58c5509.png)

**Comment by shellscape** [comment]
@red2678 why'd you close the issue?

**Comment by red2678** [comment]
@shellscape Well my requirements had changed and I no longer needed this. I really just did not want to burden the devs. I was also not sure if this is "kind of" a dupe of #149 (I am also using gulp-lesshint). 

This is would be a great feature IMO.
