### ISSUE TITLE
decimalZero behavior change

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#165]
Carrying over from @CITguy's comment in https://github.com/lesshint/lesshint/pull/160#issuecomment-201007411:

> Which is the purpose of decimalZero?
> 
> 1. to ensure that we don't have a leading/trailing decimal (.5 vs 0.5, 5. vs 5.0)?
> 2. to enforce a literal leading/trailing 0 in all cases, regardless of digits immediately adjacent to decimal (1.35 vs 01.350)?
> 3. other?

My two cents are for no. 1 but I'm not attached to anything. If we want to change the behavior, now would be a perfect time since I'm thinking we'll tag a `2.0` when we're done with the PostCSS conversion.

**Comment by CITguy** [comment]
I'm fine with option 1. I just wanted to make sure that we have that behavior documented and ensure that the linter is tested as such. I believe #160 corrects the leading zero portion of this behavior, so we'd need another PR to correct the trailing zero behavior.
