### ISSUE TITLE
Checks for valid LESS

### ISSUE THREAD

**Issue by dishad** [lesshint/lesshint#173]
``` 
table {
        position: relative;
        left: 150px;
        height: 20px;
        float: left;
}

dummytag{test}
```

This LESS code passes in the linter with "emptyRule" enabled

More examples of code that pass the linter:
```
dummytag{
dummytag}
dummytag(
dummytag)
dummytag[
dummytag]
```

**Comment by jwilsson** [comment]
Hi,
I'm getting parse errors (as expected) when trying to run `lesshint` on that code. How are you running it? Via Grunt/Gulp or something else?

**Comment by dishad** [comment]
Weird, upon fresh install of lesshint these examples get the parse error. I am guessing this is just due to using an older version of lesshint. Closing issue now.
