### ISSUE TITLE
parse error in calculated value

### ISSUE THREAD

**Issue by chrylis** [lesshint/lesshint#174]
This appears similar to #170 and may have the same resolution.

I receive a parse error on the expression

```
height: %(~'100% - %d', @top);
```

**Comment by jwilsson** [comment]
Yup, this will most certainly be solved soon with our new parser back-end in `2.0`.

**Comment by shellscape** [comment]
closing as 2.0 is suuuuuuper close to release, and gonzales-pe is no longer relevant for lesshint.
