### ISSUE TITLE
Misleading message with decimalZero rule

### ISSUE THREAD

**Issue by AoDev** [lesshint/lesshint#175]
version (npm): "lesshint": "1.5.2"

```
Warning: Snippet.less: line 18, col 20, decimalZero: 2.0 should be written with leading zero
```

I believe what is meant here is that " `0` only ", is not allowed as decimal value. This is fixed by writing `2` instead of `2.0` . (and not `02.0`)

**Comment by jwilsson** [comment]
Hmm, I think the message is misleading because of an old bug. Somewhat related to #165. I'll look into it.

**Comment by jwilsson** [comment]
Closing in favor of #165.
