### ISSUE TITLE
spaceAroundOperator negation of variable

### ISSUE THREAD

**Issue by wareczek** [lesshint/lesshint#179]
```
@someVar: 13px;

.test {
    margin-left: -@someVar;
}
```
> Warning: styles.less: line 4, col 20, spaceAroundOperator: Operators should be preceded and followed by one space.

**Comment by shellscape** [comment]
ooo nice catch!

**Comment by jwilsson** [comment]
Fix up in https://github.com/lesshint/lesshint/pull/182.
