### ISSUE TITLE
"Error: Expected opening parenthesis." with 2.0.0

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [lesshint/lesshint#183]
The parser fail on this line

```less
.progress-bar-variant(desaturate(darken(black, 10%), 10%));
```

no `.lesshintrc` file
(I can provide a minimal reproductible case if it helps)

**Comment by BenjaminVanRyseghem** [comment]
Here is the project: https://github.com/BenjaminVanRyseghem/lesshint-issue-183

run `npm test` to see the problem

**Comment by jwilsson** [comment]
Thanks for the report!

Stack trace for reference:
```
Error: Expected opening parenthesis.
    at Parser.error (/Users/jonathan/lesshint-issue-183-master/node_modules/postcss-values-parser/dist/parser.js:165:11)
    at Parser.parenClose (/Users/jonathan/lesshint-issue-183-master/node_modules/postcss-values-parser/dist/parser.js:349:12)
    at Parser.parseTokens (/Users/jonathan/lesshint-issue-183-master/node_modules/postcss-values-parser/dist/parser.js:224:14)
    at Parser.loop (/Users/jonathan/lesshint-issue-183-master/node_modules/postcss-values-parser/dist/parser.js:170:12)
    at Parser.parse (/Users/jonathan/lesshint-issue-183-master/node_modules/postcss-values-parser/dist/parser.js:99:17)
    at Object.spaceAroundCommaLinter [as lint] (/Users/jonathan/lesshint-issue-183-master/node_modules/lesshint/lib/linters/space_around_comma.js:19:41)
    at /Users/jonathan/lesshint-issue-183-master/node_modules/lesshint/lib/linter.js:132:32
    at Array.forEach (native)
    at /Users/jonathan/lesshint-issue-183-master/node_modules/lesshint/lib/linter.js:118:17
    at /Users/jonathan/lesshint-issue-183-master/node_modules/postcss/lib/container.js:81:26
```

It looks like `postcss-values-parser` doesn't like too many nested functions, the following works fine:
```less
.progress-bar-variant(darken(black, 10%), 10%);
```

I can't find anything related to the number of nested functions in any CSS spec, and Chrome runs this just fine:
```css
rgb(calc(12 + 12), 200, 128)
```

@shellscape [postcss-value-parser](https://github.com/TrySound/postcss-value-parser) parses it fine, you think it's something we should solve in `postcss-values-parser` or in `lesshint`?

**Comment by shellscape** [comment]
sounds like a `postcss-values-parser` issue to me. Best bet to fix it there.

**Comment by jwilsson** [comment]
@shellscape I think you're the one with the best knowledge of `postcss-values-parser`, you got any opportunity to take a look at it?

**Comment by shellscape** [comment]
I can take a look at it next week. I'll be unplugged tomorrow afternoon through the 20th.

**Comment by shellscape** [comment]
@jwilsson out of curiosity, I added a test mirroring the OP's test LESS and it passes. https://github.com/lesshint/postcss-values-parser/commit/69dcce19c3e6f2f04aaf38ff0a13dacfc33aca15

It looks like lesshint may not be passing the value to postcss-values-parser correctly. Using this code:

```less
.foo(bar(baz(black, 10%), 10%));
``

`.foo( .. );` is a LESS function call (of sorts). `bar(baz(black, 10%), 10%)` is the value, and that's what should be passed to values-parser. That's what I added the test for and verified that the tokenizing and node parsing is correct.

**Comment by shellscape** [comment]
So I took another look at this, and while the example I cited in my previous comment works as expected, when it's surrounded by parens, eg. `(a(b()))` the parser does fail. The quick fix is to just tell lesshint to strip the enclosing parens, but that's not a genuine fix, as that could happen elsewhere in less, not just the rule used in the OP. Working on a fix, but this is a tough one.

**Comment by shellscape** [comment]
OK I figured out the problem and fixed with this commit: https://github.com/lesshint/postcss-values-parser/commit/c77661348a9f014447bbfd79d32d97570b91dd40. I ran lesshint against that sha and everything works right, so closing this one up!
