### ISSUE TITLE
AppVeyor builds are failing due to bad path formats

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#185]
It looks like our path arguments aren't [normalized properly](https://ci.appveyor.com/project/lesshint/lesshint/build/4/job/ly04ckb0jw0ce1x9#L695).

I don't have an easily accessible Windows box to develop a fix on, any help is greatly appreciated!

**Comment by shellscape** [comment]
if we use path.join liberally, that'll get taken care of for us by node.
