### ISSUE TITLE
Working together

### ISSUE THREAD

**Issue by jeddy3** [lesshint/lesshint#186]
Hello. I'm one of the contributors to [`stylelint`](https://github.com/stylelint/stylelint) - a linter for stylesheets. I just stumbled onto this project after discovering your excellent [`postcss-values-parser`](https://github.com/lesshint/postcss-values-parser). I noticed that you've recently moved over to using PostCSS, and so I think we trying to solve very similar problems and with the same tools. Perhaps we can work together?

A month or so ago we added Less syntax support to `stylelint`. We've been busy patching up all the core rules so that they, where applicable, ignore Less constructs. We did something similar when we added SCSS-syntax support to `stylelint` i.e. making sure the core rules didn't trip-up on SCSS-syntax and ignoring SCSS constucts where applicable. This allowed a group of other developers to work on [stylelint-scss](https://github.com/kristerkari/stylelint-scss) - a plugin pack of [rules specific to SCSS-syntax](https://github.com/kristerkari/stylelint-scss#list-of-rules).

We've added [lots of features](https://github.com/stylelint/stylelint#features) to stylelint over the last year, including 140 rules. A lot of which aren't concerned with stylistic things like whitespace, but rather checking for [subtle mistakes](https://github.com/stylelint/stylelint/tree/master/src/rules/declaration-block-no-shorthand-property-overrides), [controlling specificity](https://github.com/stylelint/stylelint/tree/master/src/rules/selector-max-specificity) and [restricting what language features can be used](https://github.com/stylelint/stylelint/tree/master/src/rules/unit-whitelist). We feel like we've almost covered off most of what people would want to do with standard CSS syntax, and now we're helping the wider community write plugins for non-standard syntax (like [stylelint-scss](https://github.com/kristerkari/stylelint-scss)) and methodologies (like [BEM](https://github.com/davidtheclark/stylelint-selector-bem-pattern)).

So, I thought I'd give you guys the heads-up about the new Less support within `stylelint` in case you find it useful. Perhaps it will, and if it's something you'd like, allow you to focus on writing rules specific to Less-syntax. Please don't hesitate to give me holler if you have questions about `stylelint`. I did just notice that [it got mentioned once in the issue tracker](https://github.com/lesshint/lesshint/issues/119). FYI, we now have the [`function-parentheses-newline-inside`](https://github.com/stylelint/stylelint/blob/master/src/rules/function-parentheses-newline-inside/README.md) and [`function-parentheses-space-inside`](https://github.com/stylelint/stylelint/blob/master/src/rules/function-parentheses-space-inside/README.md) rules, which I think enforce what you're after. And the whole comma first is because we've tried to make `stylelint` as [flexible as possible](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#rules-work-together) and so we *support* all sorts of [crazy conventions](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#example-d). Putting a comma first is not something I'd do myself, but some people like it :)

**Comment by shellscape** [comment]
nice shameless plug post there :smirk:

I'm a contributor to lesshint. Personally, I like the separation of concerns that lesshint provides. The project previously use the gonzales-pe parser - another project that attempted to bridge the gap between multiple pre-processed CSS language variants - and it face-planted when the owner broke multiple syntaxes with an update, showing no apparent desire to fix it. That's where I like separation of concerns. The PostCSS-LESS syntax is easily workable, PostCSS is working wonderfully, and nothing is unfixable or too tied to one component.

it's cool you guys are passionate about your project, but I'll stick with lesshint. maybe try a blog post or pinging folks on twitter or the like in the future, instead of posting a plug in a project's issues :) 

(closing, but leaving open for comment)

**Comment by jeddy3** [comment]
> nice shameless plug post there 😏

Sorry, that wasn't my intent. Apologies if it came across like that.

> That's where I like separation of concerns. The PostCSS-LESS syntax is easily workable, PostCSS is working wonderfully, and nothing is unfixable or too tied to one component.

That's a very valid point, and one I hadn't considered. 

> it's cool you guys are passionate about your project

Likewise, you about yours.

> maybe try a blog post or pinging folks on twitter or the like in the future

I'll be sure to do this in the future.

---

One last thing. We're going to be pushing more of [our utils](https://github.com/stylelint/stylelint/tree/master/src/utils) to standalone PostCSS plugins (like we did we with [`postcss-resolve-nested-selector`](https://github.com/davidtheclark/postcss-resolve-nested-selector)), so that they are available to the wider PostCSS community. Perhaps some would be useful to you guys if you run into any similar issues with the PostCSS parser and the like.
