### ISSUE TITLE
New Linter: maxCharacterPerLine 

### ISSUE THREAD

**Issue by kenliao94** [lesshint/lesshint#191]
Hi,

I am thinking of making a linter for constraining the max number of characters per line to 100 characters to keep it consistent with ESlint. Would you like a PR for that?

Thanks,
Ken

**Comment by shellscape** [comment]
Yes please do create a PR for that!

**Comment by wareczek** [comment]
Please make it configurable. I would like to have limit on 160 chars ;)

**Comment by kenliao94** [comment]
gotcha

**Comment by kenliao94** [comment]
Hi I have got a working prototype of the linter under my forked repo. However, this is my first time making a contribution and I am not sure how to submit a code review to you guys. Could you give me some pointers or articles? Thanks.

**Comment by shellscape** [comment]
There should be a green button to submit a PR after you've pushed changes to your branch. https://help.github.com/articles/using-pull-requests/

**Comment by shellscape** [comment]
@kenliao94 were you able to figure that out?

**Comment by kenliao94** [comment]
Yes! Thank you! I just realized there's a bug in my linter. Because I used a naive approach as in I get the raw Less input of the node generated from POSTCSS. It worked, but that means every time you traverse the nodes the linter will parse the entire file again and it is not efficient. It had been a really hectic week but I will try to debug it ASAP and push a PR soon.

**Comment by kenliao94** [comment]
Hey, So I fixed that bug by setting the node type to ['root'] after seeing changes #216. However, after I merged in the change, when I am testing my code, somehow the linter is no longer running the linter I created and I literally changed nothing. I am creating a pull request, when you have time, can you take a look? Meanwhile, I am trying to figure this out myself. Thanks!
