### ISSUE TITLE
Use something like Babel or TypeScript for newer JS features

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#198]
I'm curious what your opinions of using a JavaScript (pre-)processor in the source code to enable using newer language features.

The issue came up because I wanted to so something like...
```typescript
return defaultLinters.concat(config.linters.map(linterPath => require(linterPath)));
```

...but had to switch to:
```typescript
return defaultLinters.concat(
    config.linters.map(
        function (linterPath) {
            return require(linterPath);
        }));
```

**Comment by shellscape** [comment]
For new stuff I'm all for it (see postcss-values-parser). I'd like to hold off until we have time to refactor the codebase in entirety, rather than piecemeal. I'll cede the floor to the other speakers now :)

**Comment by jwilsson** [comment]
I have to agree with @shellscape, while I obviously like new features as much as the next guy I'd also like to see a full refactor rather than bits and pieces here and there.

It's definitely something we should revisit pretty soon though!

**Comment by shellscape** [comment]
closing for now. this would involve a big effort. very much encourage any out-of-repo linters to utilize that though. I've personally started using it for all of my other projects. Node v6 supports nearly everything I need sans await/async, and that's really the only thing I'm using babel for anymore.
