### ISSUE TITLE
Available options/default value for spaceAfterPropertyColon

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#2]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
1. no_space
2. one_space (**default**)

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
Can we get code examples?
I assume it's like this?

no_space
```
div {
    property:value;
}
```
one_space
```
div {
    property: value;
}
```

**Comment by jwilsson** [comment]
Fixed in e5b0240a1b3b96d2b60bfba877c5240057e63461.

Any opinions on the default values/available options?

**Comment by kokarn** [comment]
Great work!

No not really, tabs perhaps?

**Comment by kokarn** [comment]
Closing this as no other options that make sense have been presented.
