### ISSUE TITLE
emptyRule 2.0 bugs

### ISSUE THREAD

**Issue by wareczek** [lesshint/lesshint#200]
```css
.header-def(@rules) {
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        @rules();
    }
}
```
> Warning: mixins.less: line 1, col 1, emptyRule: There shouldn't be any empty rules present.
> Warning: mixins.less: line 2, col 5, emptyRule: There shouldn't be any empty rules present.
> Warning: mixins.less: line 8, col 17, spaceBeforeBrace: Opening curly brace should be preceded by one space.

**Comment by shellscape** [comment]
I'm on the case

**Comment by wareczek** [comment]
nice @shellscape :+1:

**Comment by wareczek** [comment]
@shellscape sad news :( on actual master it's still occurs, but only one error:

> Warning: mixins.less: line 2, col 5, emptyRule: There shouldn't be any empty rules present.

**Comment by shellscape** [comment]
@wareczek with the same test less? I used (nearly) exactly the less you had posted about in the spec and it's passing: https://github.com/lesshint/lesshint/commit/adb93cea4c50e7d1c66742595c04fb52dea50ba9#diff-7891ca8c84502cfb7b7b1a132f146393R83

**Comment by wareczek** [comment]
Yes, same. But in your test you don't have newlines

**Comment by shellscape** [comment]
yeah newlines didn't change the condition of the test at all so I removed them for brevity. I ran into a weird situation with qualifyingElement where the specs were passing but when used in `bin/lesshint` it was failing. this could be the same situation. I'll have another look

**Comment by shellscape** [comment]
#210 should resolve the remaining issues here. here's hoping!
