### ISSUE TITLE
2.0 Release

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#203]
@jwilsson @kokarn I think that 2.0 is ready for release once ~~#196~~ and ~~#183~~ (got em done) are wrapped up. We've seen a few minor bugs but nothing major reported. What says ye?

**Comment by tkazec** [comment]
Has the latest been published to `lesshint@next`? I'm still seeing the error described in #192.

**Comment by shellscape** [comment]
@tkazec if you don't see an updated version, it hasn't been pushed. `npm info lesshint` will show you all you need in the future.

**Comment by tkazec** [comment]
@shellscape If you take a look at that issue, I did post there a couple weeks ago.

The README specifically states to "help us out with testing 2.0, install with `npm install lesshint@next`", so... it would be great if you could update `@next` and/or the README.

**Comment by kokarn** [comment]
Sorry if i've been pretty off. I've followed along on all the work you guys have done and it does indeed both look amazing and ready.

I say let's go for it. Just skipping gonzalez is such a big thing that we should really try to publish it and fix any upcoming bugs after the fact.

:+1: lgtm

**Comment by jwilsson** [comment]
Sorry that I've been off, too many other things going on.

@shellscape Great work the last couple of days! I'm trusting you with the fixes, if we're good I'll add some docs for custom linters and tag `2.0` tonight 😃

**Comment by shellscape** [comment]
@jwilsson yeah! do eeeeeet!

**Comment by jwilsson** [comment]
`2.0` tagged and published! 🎉 

Great work and a huge thanks to everyone involved!
