### ISSUE TITLE
External Linters: Add tests for failing linters

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#205]
As per https://github.com/lesshint/lesshint/pull/197#discussion_r67812908, there's missing test coverage for the case of loading linters being broken such that only one of the linters gets included.

**Comment by shellscape** [comment]
ah I thought you were just gonna make a new pull request :)

**Comment by JoshuaKGoldberg** [comment]
Ha, yes. This will remind me.

**Comment by shellscape** [comment]
@JoshuaKGoldberg updated the issue name with a little context, because I keep forgetting what it's for :)

**Comment by JoshuaKGoldberg** [comment]
Not at all :)

**Comment by shellscape** [comment]
@JoshuaKGoldberg ping on this one

**Comment by JoshuaKGoldberg** [comment]
Confirmed - will try to get done soon.
