### ISSUE TITLE
Abusive contributions

### ISSUE THREAD

**Issue by tkazec** [lesshint/lesshint#208]
I recently asked about the status of the `@latest` npm tag in issue #203. @shellscape dismissed my question, replying that my comment was off-topic and telling me to post in my original issue #192.

Unfortunately, I had already posted in that issue a couple weeks back, and my question remained, as did the message regarding `@latest` in the README. I replied saying as much. Coming back a couple hours later, all the relevant comments were *completely erased*, with no other changes or updates.

While a project's moderation is ultimately 100% up to its contributors, I find this kind of behavior disappointingly hostile. Sorry for not being exactly on-topic, but I did raise valid concerns, and *scrubbing them from history* is not an acceptable response. Please be nice.

(see also: #186)

**Comment by kokarn** [comment]
Sorry about that, it's been a bit stressful around here with me not doing what I should.
IIRC the comment in the readme is actually incorrect. However, it is possible to install directly from GitHub. You can use the following command for that `npm install https://github.com/lesshint/lesshint.git`.

Always glad for the extra help when it comes to testing :)

**Comment by shellscape** [comment]
@tkazec nothing was abusive, nothing was mean, nothing wasn't nice. you posted off-topic, were called on it, and then decided to post about it _again_ in the same thread. your comments should have been posted on the relevant issues, even if a follow up. we're notified of comments on issues that are already closed, and it gives us the opportunity to re-open if warranted. standard github procedure. hijacking other issues meant for meaningful discussion on separate topics is not appropriate, and that's looked poorly upon on any repo on github.

sorry man, but no one's out to hurt your feelings. I'm afraid you're simply being way overly sensitive here.

**Comment by tkazec** [comment]
@shellscape *Deleting comments*, especially *unresolved and in good faith*, is far more frowned upon on GitHub. I don't particularly care and my feelings were certainly not hurt, but you are being blatantly caustic, and others may care more. We are all in the Open Source community together, and I would hate to see this kind of thing happen to someone else ... unfortunately, #186 is significantly more hostile, which is what actually prompted me to post in the first place.

@kokarn Thank you.

**Comment by shellscape** [comment]
@tkazec _posting comments_ that are _blatantly off-topic_, even if posted in good faith, is just a big no-no no matter how you choose to justify it. you'll notice that several issues are re-opened (one was just this morning!) after comments are made with further proofs/cases for testing, additional related bugs, etc. Those comments tend to be on the issue the comments are actually trying to address. And not a single person has had issue with how anyone's interacted. We've guided many folks through new contributions, we've welcomed contributions that needed guidance and massaging and have generally been completely open to everyone and everything.

if you're applying a hostile tone, or choosing to interpret verbiage as hostile, that's your call. but that's on the individual. you're certainly welcome to your opinions. You've cited #186 a few times now - you don't like it, you've made that clear. I tend to find this as just pot-stirring, as there's nothing remotely hostile here, despite your interpretation.

@jwilsson is the gracious owner of the project and repo, and should he choose to agree, I'll have no issue with that, and I'm sure he'll act reasonably and accordingly. If he chose to remove my status as a contributor, I'd accept that without malice as well. As @kokarn has addressed the portion of this issue that was technical, I'm locking the conversation. That's not a hostile action either - that's a reasoned action - aside from the technical aspect of the issue, the bulk is of an interpersonal nature. The others may feel free to unlock/reopen for discussion and I'll respect that, but I'll not be participating in the perceived hostility debate further.

**Comment by jwilsson** [comment]
Really sorry for my silence on this (and other issues too), been way too much other things going on. 

I agree that deleting comments isn't OK but I think most of us get a lot of notifications every day and one more just adds to the stress. I'm sure someone would have replied in #192. And as I think we all know, communication on the Internet is hard. 

Again, @tkazec I'm sorry to hear that you feel this way but as @kokarn said, I think we've all been stressed about getting `2.0` out and juggling that with other things.

With this said, I'll leave the issue locked since we've all vented our thoughts and opinions and I don't think we'll get any further on this matter. If someone wants to unlock it, I won't mind of course.
