### ISSUE TITLE
spaceAroundComma 2.0 again :)

### ISSUE THREAD

**Issue by wareczek** [lesshint/lesshint#209]
```
.test1,
.test2:not(.test3) {
    width: 100%;
}
```
> Warning: articles.less: line 1, col 7, spaceAroundComma: Commas should be followed by one space.

**Comment by shellscape** [comment]
@wareczek i'll have a look. probably going to end up using the same fix as for spaceBetweenParens

**Comment by shellscape** [comment]
@wareczek hopefully that last PR fixed it for good

**Comment by wareczek** [comment]
@shellscape yes, adding `"spaceAroundComma": {"allowNewline": true}` (on branch `fix-119-proposal`) fixed that but… example from this issue is not multiline. only two selectors :(

**Comment by shellscape** [comment]
@wareczek well it technically is multiline, as there's a newline following the comma.

**Comment by wareczek** [comment]
Problem is about parenthis in pseudo class `:not()`. Works fine with this:

```
.test1,
.test2.test3 {
    width: 100%;
}
```
and there's also newline :P

**Comment by shellscape** [comment]
@wareczek there's a space after that comma in your code example, so I'm not sure how to interpret what you're saying.

**Comment by wareczek** [comment]
Look at code from first post.

this code generates error:
```
.test1,
.test2:not(.test3) {
    width: 100%;
}
```
and this not:
```
.test1,
.test2.test3 {
    width: 100%;
}
```

both have newline, but first have `:not()`

**Comment by shellscape** [comment]
oye. rough morning here :) OK ill take a look. the PR is still open so I can fiddle with it

**Comment by wareczek** [comment]
finally :D :tada:

**Comment by shellscape** [comment]
so, we've got a blocking error in postcss-less that's causing the error with the `:not` in the selector. I'm tracking it on https://github.com/webschik/postcss-less/issues/56

I'll see if there's a workaround in the meantime...

**Comment by shellscape** [comment]
should be all good now. ran both of your examples in specs and through the bin.
