### ISSUE TITLE
finalNewline and trailingWhitespace linter bugs

### ISSUE THREAD

**Issue by garethwhittaker** [lesshint/lesshint#216]
Since moving over to PostCSS it doesn't look as though these two linters have been firing.

Their lint functions don't seem to be triggered when using `nodeTypes: ['root']`. Changing this to `nodeTypes: ['rule']`, does fix this but the internal logic for these looks to be incorrect atm.

**Comment by shellscape** [comment]
hm, that's curious. the specs definitely wouldn't pass if that were the case. please do dive a little deeper on this one. I'd love to find out if this were an environment condition on your end or a gap in our specs.

**Comment by shellscape** [comment]
@garethwhittaker ping!

**Comment by garethwhittaker** [comment]
looking at the specs, I can see the lint function is being manually called:
`var result = spec.linter.lint({}, ast.root);`

but on both my windows pc and macbook, the `lint` function isn't being triggered for these linters to perform their checks.

**Comment by garethwhittaker** [comment]
investigating a little further as to why these aren't firing:

File: `linter.js`

```
ast.root.walk(function (node) {
        linters.forEach(function (linter) {
            // .....

            // Node type(s) not applicable, bail
            if (Array.isArray(linter.nodeTypes) && linter.nodeTypes.indexOf(node.type) === -1) {
                // GETTING IN TO HERE FOR A NUMBER OF LINTERS
                return;
            }

            // .....

            // NEVER GETS THIS FAR.
            lint = linter.lint.call(linter, options, node);
```

**Comment by shellscape** [comment]
thanks for digging on that. I'm planning on getting a fix up for this whenever my week let's me. I'm suspecting that `ast.root.walk` doesn't include `ast.root` which is a `Root` type node. probably need an elegant solution to that.
