### ISSUE TITLE
Feature request: MSBuild integration?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#217]
Is there any pre-existing work around integrating lesshint with MSBuild or other build systems?

Context: I'd like to integrate lesshint into an MSBuild build system, so that it runs at compile-time similar to [TSLint.MSBuild](https://github.com/JoshuaKGoldberg/TSLint.MSBuild).

**Comment by shellscape** [comment]
I haven't used a windows pc (for more than flashing my android device) in years. I'll sit back and watch this one from the sidelines...

**Comment by JoshuaKGoldberg** [comment]
https://www.nuget.org/packages/Lesshint.MSBuild/0.1.0
