### ISSUE TITLE
Push to nuget.org as a part of the release process?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#218]
Corollary to https://github.com/lesshint/lesshint/issues/217: it would be useful to have lesshint as a NuGet package so MSBuild systems can pull it in easily.

I've gone ahead and made a [lesshint-nuget repo](https://github.com/JoshuaKGoldberg/lesshint-nuget) with tiny scripts to package lesshint as a NuGet package, and pushed 2.0.0 to NuGet: https://www.nuget.org/packages/lesshint/2.0.0

Questions for you:
* Do you want ownership of the repo and/or NuGet package?
* Would you be able to include publishing to NuGet as a part of your release process?

**Comment by shellscape** [comment]
@JoshuaKGoldberg do they have a nuget binary for non-windows machines these days? it's been ages since I used nuget.

**Comment by JoshuaKGoldberg** [comment]
Err, I haven't tried it. There's Mono support but there may be issues:

https://docs.nuget.org/consume/nuget-faq

**Comment by shellscape** [comment]
@jwilsson has to make the call on this, as he is the fella who does the package publishing.

here's my $0.02: looking at the source on https://github.com/NuGet, it's pretty tightly integrated into visual studio (sharpdevelop, xamarin studio) and powershell. from what I've read, one would need to have xamarin studio installed, and that's a pretty big ask. it's a shame they don't have a cross-platform simple binary that one can use like npm/bower/webpack. there's this https://www.npmjs.com/package/nuget but one needs to have mono installed. this may end up being just too ms-centric.

**Comment by kokarn** [comment]
I'm on Windows since I started my new job so maybe I could help with that?
Either that or we set up a Windows machine on Azure or something to do this
automatically

**Comment by shellscape** [comment]
@kokarn that's an excellent idea, an automated script perhaps? could possible use an ifttt recipe similar to https://ifttt.com/recipes/220887-get-notified-when-new-async-npm-packages-are-published to kick it off.

**Comment by JoshuaKGoldberg** [comment]
Yeah I talked to some of the NuGet folks, right now there are two native options:
* Use mono + nuget.exe (see [compatibility](https://docs.nuget.org/consume/compatibility)
* Have the .NET SDK installed

I'll poke around and see if anybody's had luck using [mkbundle](http://www.mono-project.com/archived/guiderunning_mono_applications/) to bundle a nuget.exe that you'd be able to use without installing anything.

**Comment by jwilsson** [comment]
I'm on a Mac as well so I think it's better if one of the Windows guys (@JoshuaKGoldberg or @kokarn) are responsible. But the automated script idea sounds really cool too.

**Comment by shellscape** [comment]
@JoshuaKGoldberg can we close this one? saw you were pushing to NuGet on the last release.

**Comment by JoshuaKGoldberg** [comment]
Sure.
