### ISSUE TITLE
Available options/default value for attributeQuotes

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#23]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
1. double
2. single (default)

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by CITguy** [comment]
Can we add support to allow selectors for value-less (a.k.a. boolean) attributes?

```html
<input disabled />
```

```less
input[disabled] {
    color: #ccc;
}
```

**Comment by jwilsson** [comment]
Of course, I noticed the bug now. 

Are you interested in submitting a PR?

**Comment by CITguy** [comment]
I would. I may have some time this weekend to familiarize myself with the inner workings.

**Comment by CITguy** [comment]
See #54

**Comment by kokarn** [comment]
Closing this as the only option we wanted have been merged.
