### ISSUE TITLE
Rule `importPath` with `filenameExtension = true` complains about inline import

### ISSUE THREAD

**Issue by trygveaa** [lesshint/lesshint#236]
If I have the rule `importPath` with `"filenameExtension": true`, and use an inline import, lesshint complains that the import should include the file extension even when it does.

E.g. this import:

```
@import (inline) 'variables.less';
```

Gives this error:

```
Warning: main.less: line 13, col 9, importPath: Imported file, "(" should include the file extension.
```

I'm using the currently latest version of lesshint, 2.0.2.

**Comment by shellscape** [comment]
Looks like we need to account for import options http://lesscss.org/features/#import-options

**Comment by shellscape** [comment]
Opened this issue with the postcss-less project: https://github.com/webschik/postcss-less/issues/57 which would address this. There are several issues that are nearly a month old with no replies. Really, really hoping that project hasn't gone stale. @jwilsson 

In the meantime there may be something we can do with the values parser to backfill the problem.

**Comment by jwilsson** [comment]
I don't think it's gone stale, and I'll see if I can help out there a little bit too.
