### ISSUE TITLE
Available options/default value for comment

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#24]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
Regexp for allowed comments.

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
I'd suggest changing the default value to allow all comments. Removing comments is something a minifier should do, not the hinter imo.

**Comment by CITguy** [comment]
With the plan to add support for inline comments for purposes of disabling linters, you're more likely to see a mix of comment types in a file. Additionally, I agree with @kokarn, that it's the job of the minifier to remove comments. IMO, I see no value in this linter for use in projects I work on. 

I vote this default to `disabled`.

**Comment by jwilsson** [comment]
Perhaps we should even remove it? I don't have any problems doing it if everyone's onboard.

**Comment by kokarn** [comment]
Hmm, i'd rather have it disabled than removed. 
Even if we all agree it's not that important there is probably people who'd want this :)
