### ISSUE TITLE
Fails when encounters a dead symlink

### ISSUE THREAD

**Issue by runarberg** [lesshint/lesshint#251]
This happens a lot in my meteor app. Meteor creates a symlink inside the `.meteor` directory, then later becomes dead, and then lesshint won't work unless I manually remove it (which is not possible with our CI system).

``` bash
mkdir -p /tmp/lesshint/styles/
cd /tmp/lesshint/
npm i lesshint
touch styles/style.less
ln -s $(pwd)/deadlink styles/deadlink
```

```
$ ls -l styles/
lrwxr-xr-x  1 user  group  21 Sep 12 11:31 deadlink -> /tmp/lesshint/deadlink
```

```
$ ./node_modules/.bin/lesshint styles/
An unkown error occured, please file an issue with this info:
Error: ENOENT: no such file or directory, stat 'styles/deadlink'
    at Error (native)
```

**Comment by runarberg** [comment]
This might also be related to lesshint not working as a [flycheck] checker in my emacs setup.

Flycheck always outputs this error message when I enable it inside a less file:

```
Suspicious state from syntax checker less: Checker less returned non-zero exit code 70, but no errors from output: An unkown error occured, please file an issue with this info:
Error: ENOENT: no such file or directory, stat '-'
    at Error (native)

Checker definition probably flawed.
```

[flycheck]: http://www.flycheck.org/

**Comment by shellscape** [comment]
Probably needs to check each file for that, around https://github.com/lesshint/lesshint/blob/master/lib/lesshint.js#L16.

**Comment by jwilsson** [comment]
Yeah, I guess we should check if the file/link exists before trying to do anything with it.

@runarberg Would you be interested in submitting a PR?

**Comment by runarberg** [comment]
Sure, I'll see what I can do :)

**Comment by runarberg** [comment]
https://github.com/dfilatov/vow-fs/issues/24

**Comment by runarberg** [comment]
Also related https://github.com/eslint/eslint/issues/3490. However, eslint differs as it allows ignoring directories (not just globs), so adding `.meteor` to `.eslintignore` is sufficient to for my particular issue since that is where the meteor build tool creates all (possible dead) symlinks.

**Comment by jwilsson** [comment]
Please correct me if I'm wrong, but shouldn't something like this work?
```js
{
    "excludedFiles": ["**/.meteor/**/*.less"],

    // Other rules...
}
```

**Comment by runarberg** [comment]
No it won't because the file is visited with `fs.stat` before it is ignored with a glob match. Unlike eslint which wont visit any files and sub-directories belonging to an ignored directory.

**Comment by jwilsson** [comment]
Ah, of course! Sorry about that.

**Comment by jwilsson** [comment]
Sorry for the silence.

But I've been thinking about this over the last weeks and I think we got too caught with symlinks. I think the real issue is the fact that `excludedFiles` doesn't work quite as expected. I think I have an idea on how to solve it while retaining backwards compatibility meaning `excludedFiles` will run before any filesystem operations, so my example from above will work.

I'll try to have something to show during the weekend.

**Comment by shellscape** [comment]
@jwilsson we could also use `globby` and it's ignore patterns, as a base for the files to lint. That'd exclude it before we even get started looking at files.

**Comment by jwilsson** [comment]
@shellscape I think we're fine with `minimatch` for now. 

I got the suggestion up in #285 and I'd like some feedback on it.

**Comment by jwilsson** [comment]
Closing this since `excludedFiles` will work as expected in `3.0`.
