### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by dinony** [lesshint/lesshint#254]
Hello,

lesshint is listed in the  [plugins list](http://lesscss.org/usage/#plugins).
I'm working on a project using gulp and I would like to use lesshint as a plugin. Like in this [example](https://github.com/plus3network/gulp-less#using-plugins).

However, it seems that this interface is not implemented. 

<img width="359" alt="screen shot 2016-09-14 at 11 40 48" src="https://cloud.githubusercontent.com/assets/2547965/18507315/268360d2-7a70-11e6-8500-4a78e6443456.png">

Am I missing something or how do I use lesshint as a plugin (via gulp)?

Thanks,
dinony

**Comment by kokarn** [comment]
Does it have to be a direct plugin or can you use the [gulp-lesshint](https://github.com/lesshint/gulp-lesshint) package instead?

**Comment by dinony** [comment]
I would rather prefer to use it as a direct plugin, than to use small (possibly unmaintained) gulp packages.

**Comment by kokarn** [comment]
Yeah I hear you, doing the same thing myself. I know we got listed on lesscss a while back and there might be something that's changed with what's required to be a less plugin. I'll see if I have time to look at that but @jwilsson is the man with the plan (and skills)

**Comment by jwilsson** [comment]
Hi,
Thanks for reaching out!

While it's true that lesshint isn't an real less plugin I think it should be pretty easy to wrap it in one and create a proper one without us adding anything in lesshint. [less-plugin-lesshat](https://github.com/bassjobsen/less-plugin-lesshat) might be of some help to anyone interested in writing a plugin (in addition to the one @kokarn posted).

(Just btw, gulp-lesshint is maintained by us so it won't go unmaintained :))

**Comment by dinony** [comment]
Hello,
thanks for your answers!
If it's not too much work it would be great if you could adapt the plugin interface. 
In the meantime I will use the mentioned gulp plugin.

Thanks again!

**Comment by jwilsson** [comment]
I don't think we'll implement the Less plugin interface in the main lesshint project, but if @kokarn (or anyone else for that matter) is interested in creating a standalone Less plugin wrapping lesshint we could push for that in the Less docs instead.

**Comment by kokarn** [comment]
Maybe we should consider getting removed from lesscss.org until that is fixed? With the rise of plugins for applikations like Babel I feel like this is something that will bite quite a few more people in the ass :/

**Comment by jwilsson** [comment]
Closing this since it's out of scope for `lesshint`. But if anyone is interested in building a Less plugin I'd be happy to link to it in the README.
