### ISSUE TITLE
Less merge (comma or space) should be excluded from "duplicateProperty"

### ISSUE THREAD

**Issue by MichelGratton** [lesshint/lesshint#257]
In LESS there is feature use to merge property with a comma or a space by adding respectively "+" or "+_". These properties can be duplicated inside a single bloc. In my case it's inside a mixins. I can add all properties using this feature in the exclude property. But I think, this should be automaticaly exclude for all properties ending with "+" or "+_".

See: http://lesscss.org/features/#merge-feature

**Comment by shellscape** [comment]
Please provide some sample LESS

**Comment by MichelGratton** [comment]
Here two very basic mixins to test it. First example will merge two box-shadow property with a comma and the second mixin will merge to property with a space.
```less
.sample-merge-comma(@addInset: false) {
    box-shadow+: 0 0 10px #555;
    & when not (@addInset = false) {
        box-shadow+: inset 0 0 5px #222;
    }
}
```
---
```less
.sample-merge-space(@addRotate: false) {
    transform+_: scale(2);
    & when not (@addInset = false) {
        transform+_: rotate(15deg);
    }
}
```
