### ISSUE TITLE
Available options/default value for trailingZero

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#26]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
1. exclude_zero (default)
2. include_zero

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
I'd suggest changing the default value to include_zero. Removing extra zeroes is something a minifier should do, not the hinter imo.

**Comment by CITguy** [comment]
Could we combine `trailingZero` and `leadingZero` into a `padZero` (or other appropriate name)? 

This linter would accept the following options:

* `leading` (default)
* `trailing`
* `none`
* `both`

Examples

```less
font-size: .5em;   // none
font-size: 0.5em;  // leading
font-size: .50em;  // trailing
font-size: 0.50em; // both
```

**Comment by kokarn** [comment]
:+1: Makes it more consistent with the other linters as well

**Comment by jwilsson** [comment]
@CITguy Nice idea. You wanna take a stab at implementing it?

**Comment by CITguy** [comment]
I can see what I can do. Does `padZero` work as a linter name, or does anybody have a better suggestion?

**Comment by kokarn** [comment]
I feel like it's not great but I can't come up with a better one. It's not really a zero padding, it's more like a zero enforcing linter. Maybe ```forceZero```, ```valueZero```, ```decimalZero``` or something like that?

**Comment by CITguy** [comment]
`decimalZero` works. I'll get working on this, today.

**Comment by CITguy** [comment]
Good news. I've got the functionality working. I just need to clean things up before submitting a PR. Should have it submitted sometime this evening.

**Comment by kokarn** [comment]
Great! I'll close this for now so we can continue discussion in #69
