### ISSUE TITLE
Report parse errors the same as regular ones

### ISSUE THREAD

**Issue by wohanley** [lesshint/lesshint#263]
background: [#261](https://github.com/lesshint/lesshint/pull/261)

When lesshint hits a line it can't parse, it stops and throws an exception. It might be better to add a parse error for that line to the results and keep going.

**Comment by jwilsson** [comment]
Sorry for the lack of activity here @wohanley!

@lesshint/team Do we want to go through with this? The question is whether or not we want to add invalid inline config comments to the results returned.

For example:
```less
// lesshint invalid
.foo {
...
}
```

would be emitted as

```bash
Warning: file.less: line 1, col 1, invalidComment: "invalid" is a not a valid config comment.
```

**Comment by jwilsson** [comment]
As of `4.6.0`, invalid inline configuration comments will be included in the linting results.
