### ISSUE TITLE
Rule proposal: spaceAroundBang

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#267]
A rule to enforce spaces around the exclamation mark/bang in `!important` etc.

Suggested options:
- `none`
- `before`
- `after`
- `both`

When `none`:

``` less
color: red!important; // Valid
color: red !important; // Invalid
color: red ! important; // Invalid
color: red! important; // Invalid
```

When `before`:

``` less
color: red !important; // Valid
color: red!important; // Invalid
color: red ! important; // Invalid
color: red! important; // Invalid
```

When `after`:

``` less
color: red! important; // Valid
color: red !important; // Invalid
color: red!important; // Invalid
color: red ! important; // Invalid
```

When `both`:

``` less
color: red ! important; // Valid
color: red! important; // Invalid
color: red !important; // Invalid
color: red!important; // Invalid
```

**Comment by shellscape** [comment]
Do we have other symbols/glyphs/characters that we check in a similar manner? (asking for posterity) We might consider a linter plugin with config to allow for checking any number of characters with varying config. Would negate the need for separate linters.

**Comment by jwilsson** [comment]
Marking as "blocked" due to https://github.com/shellscape/postcss-less/issues/87.
