### ISSUE TITLE
singleLinePerProperty rule should support single-line definitions

### ISSUE THREAD

**Issue by CASandmann** [lesshint/lesshint#269]
My team just started using this linter and it has already helped out tremendously.  One rule we would like to see altered however, is the `singleLinePerProperty` rule.  By name, this sounds like a rule that we should support, but it causes a warning on simple lines of this format:

```
.ion-help-circled { cursor: pointer; }
```

I feel like there should be a separate rule governing whether or not you should be allowed to put attribute definitions on the same line as the selector.  As it stands, we have to disable this rule, even though we would like to be able to catch definitions that look like:

```
.section-title {
    font-size: 16px; margin-bottom: 20px;
}
```

**Comment by kokarn** [comment]
Sounds like a bug, yeah. @jwilsson ?

**Comment by jwilsson** [comment]
I think it's working as expected but that we need a `allowSingleLineRules` (or similar) option to allow those types of rules.
