### ISSUE TITLE
Available options/default value for zeroUnit

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#27]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
1. keep_unit
2. no_unit (default)

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
I'd suggest changing the default value to keep_unit. Removing unneccessary units is something a minifier should do, not the hinter imo.

**Comment by CITguy** [comment]
I have no preference on default, but I'll be using `no_unit` for all my projects.

**Comment by kokarn** [comment]
That would be a configuration rather than a default i'd say ;)
To be consistent with the other linters we should probably keep this to linting and let the minifiers do the rest.

**Comment by jwilsson** [comment]
I don't have any preferences either, so I say we go with `keep_unit` and let minifiers handle it.

**Comment by shellscape** [comment]
Just to play devil's advocate, I'm going to question the need for this linter at all. If minification processes will strip or keep units on zero values, why are we bothering to lint them? Does this sort of consistency across files in a project/org aid readability, or does `0` and `0px` read the same?

(This isn't something we restrict in our org)

**Comment by kokarn** [comment]
Hmm, interesting point. 
Gonna have to think about this one ;)

**Comment by kokarn** [comment]
So this is the last blocking thing for 1.0.

I suggest we set it to ```keep_unit``` and discuss if the linter is needed at all at a later date.

**Comment by CITguy** [comment]
+1 for `keep_unit`. Let's get 1.0 out the door.
