### ISSUE TITLE
Negative attribute value throws CssSyntaxError

### ISSUE THREAD

**Issue by cheeZery** [lesshint/lesshint#270]
```
.foo {
    margin: -10px;
    color: red;
}
```
results in the following output
```
edp INFO asset/less/ours/foobar.less
edp WARN → CssSyntaxError: TypeError: Cannot read property 'type' of undefined
```

[Output of lesslint -v](https://github.com/lesshint/lesshint/files/542117/lesslint.-v.txt)

**Comment by shellscape** [comment]
@cheeZery this project is *lesshint* whereas your output seems to be for *lesslint*. the repo for lesslint is https://github.com/ecomfe/node-lesslint/issues. did you post the issue on the wrong project?

**Comment by cheeZery** [comment]
Whoops, you're totally right, I installed lesslint by mistake :D I'm sorry..

**Comment by shellscape** [comment]
No worries.
