### ISSUE TITLE
Allow .lesshintrc options to be true instead of { "enabled": true }

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#272]
This works:

```json
	"attributeQuotes": {
		"enabled": true
	},
```

This does no:

```json
	"attributeQuotes": true,
```

Would it be as simple as changing the `if (!options || (options && !options.enabled)) {` under the `ast.root.walk` under `linter.js`' `runChecks`?

**Comment by jwilsson** [comment]
I've thought about this myself recently and I like it! Changing that line should be enough, yeah.

**Comment by shellscape** [comment]
Yeah it's better than ESLint's array settings schema, that's for sure.
