### ISSUE TITLE
newlineAfterBlock not working in 2.2.0

### ISSUE THREAD

**Issue by VolleMelk** [lesshint/lesshint#274]
During a code review I noticed our build was passing even though I had the following less:
```
img.poster {
  width: 100%;
}
img.playbutton {
  left: ~"calc(50% - 10px)";
  position: absolute;
  top: ~"calc(50% - 10px)";
}
```

We have enabled the newlineAfterBlock linter with
```
  "newlineAfterBlock": {
    "enabled": true,
    "severity": "error"
  },
```

Our buildservers are automatically updated. When I ran the linter on my development computer the build failed as expected:
>Error: ipmobile.less: line 1186, col 7, newlineAfterBlock: All blocks should be followed by a new line.

After I updated my globally installed lesshint using **npm update -g lesshint** and ran the linter again, the linter passed.

**Comment by jwilsson** [comment]
I can confirm this, looks like a regression from ed2c9f6df2811d696067bf5f29fdde19a53a4467. I'll take a look at it.
