### ISSUE TITLE
Auto-fix Lesshint bugs?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#278]
I’d like to make a project to automatically apply fixes for lesshint failures. A big blocker from adopting more linting for a lot of teams (mine included) is the time it takes to fix existing failures. I’ve started a  [rough draft](https://github.com/joshuakgoldberg/automutator) project that takes in and applies waves of suggested fixes, such as from a linter like lesshint.

A potential technical implementation could be:

1. Allow for an optional `suggestFix` method for linters that takes in failures and outputs some POJO representation of the fix
    * My proposal for the format of such as fix: [automutate](https://github.com/JoshuaKGoldberg/automutate) ([abstract mutation spec](https://github.com/JoshuaKGoldberg/automutate/blob/master/src/mutation.ts) / [sample mutator](https://github.com/JoshuaKGoldberg/automutate/blob/master/src/mutators/textDeleteMutator.ts))
2. Add a new reporter that just reports these fix suggestions as JSON

What are your thoughts on this? Is it something you’d be interested in having me work on?

*Edit: Discovered issues*:
* #287: Lesshint reports line and column number for errors, but thanks to file inconsistencies with `\n` verses `\r\n` endlines those aren't directly mappable to absolute character positions in files. This would require remembering file endlines and using them to output absolute `"position": number`s in error complaints.
* #283: In order to get the full CLI logic, you need to run `cli.js`. This needs to either take in a different `onExit` than the `exit` package or have its logic refactored out.
* ~~#284: Custom reporter objects should be allowed, so that we don't have to go with one that directly `console.log`s. Alternately passing a stream that reporters can stream to (with console logging as the default) could work.~~ Never mind - works!

**Comment by kokarn** [comment]
Sounds very useful. :+1:

**Comment by shellscape** [comment]
Some links for reference:

https://github.com/stylelint/stylelint/issues/330 - good discussion around the same for stylelint.
https://github.com/morishitter/stylefmt - may make sense to ping this guy about supporting lesshint. seems to be a very active project.

**Comment by JoshuaKGoldberg** [comment]
@shellscape interesting, I hadn't seen stylelint yet! Thanks for bringing it up.

Re https://github.com/lesshint/lesshint/issues/186, I don't quite follow what you mean by "separation of concerns" (and haven't yet delved into PostCSS). What do you mean?

I've started prototyping this for fun. It's mostly ~workable, but with a few issues I'll edit into the OP.

**Comment by shellscape** [comment]
(being sincere, not at all trying to be remotely patronizing) https://en.wikipedia.org/wiki/Separation_of_concerns

> In computer science, separation of concerns (SoC) is a design principle for separating a computer program into distinct sections, such that each section addresses a separate concern.

I much prefer how modular and flexible Lesshint is, as credit to @jwilsson for the original design that's allowed it to be. Since I've been involved, we've refactored the linters, added reporter support and even swapped out our AST generator. And it was all relatively painless. Lesshint separates the concerns and intent of the lib in a way that's very much agreeable with how I like to work. And that's all strictly my personal opinion. Lesshint may not be the juggernaut that Stylelint has become, but I sure do love the project.

**Comment by JoshuaKGoldberg** [comment]
No offense taken :) I was more curious about how you meant it with regards to the project design.

**Comment by jwilsson** [comment]
I really like the idea!

Let me just think approaches for a few days :)

**Comment by JoshuaKGoldberg** [comment]
Cool. I've started a rough draft at https://github.com/autolint/autolesshint - note that it assumes an `npm link`ed version of `lesshint` with some of the proposed changes.

**Comment by jwilsson** [comment]
Alright, the approach I think I like the best is using a new reporter which would return the suggested fixes which would allow `automutate` (or another tool etc.) to do what's necessary with the results. 

BTW, just out of curiosity, did you talk to the `stylelint` and/or `stylefmt` guys?

**Comment by JoshuaKGoldberg** [comment]
> new reporter which would return this suggested fixes

Agreed!

Would you prefer this be built into `stylelint` or separate tool(s)?

> talk to the `stylelint` and/or `stylefmt` guys

Yes: https://github.com/stylelint/stylelint/issues/2059

**Comment by jwilsson** [comment]
@JoshuaKGoldberg I think we should keep it as a separate tool for now, if we want to we can always reevaluate it at a later time.

I'll try and help out as much as I can!

**Comment by JoshuaKGoldberg** [comment]
Awesome - the initial blockers are out of the way so what's left is:
1. Add an allowance for a `suggestFixes` method on linters
2. Add `suggestFixes` to as many rules as can support it.

I'm assuming you don't want 1 without 2 (random undocumented functionality) so I'll put up a PR with the design proposal and add rules as I can.

**Comment by jwilsson** [comment]
I'm gonna close this since we discussed this and came to the conclusion of keeping it as a separate tool in #307.
