### ISSUE TITLE
Allow an onExit other than the exit package

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#281]
When trying to run `lesshint` via...

```javascript
const lesshint = require('lesshint/lib/cli');
const settings = { /* ... */ };

lesshint(settings)
    .then(statusCode => console.log(`Finished with status ${statusCode}`})
    .catch(error => console.error(`Error: ${error}`));
```

...nothing gets logged in the happy case because [exit](https://www.npmjs.com/package/exit) is called at the end.

If we change one line in cli.js, it becomes possible to provide a custom `onExit` callback:

```javascript
    exitPromise.always(function (status) {
        // exit(status.valueOf());
        (program.onExit || exit)(status.valueOf());
    });
```

it would be possible to provide a custom onExit.

```javascript
const settings = {
    onExit: () => {}
};
```

Required for https://github.com/lesshint/lesshint/issues/278.

In case you're wondering why I'm not using the recommended `require('lesshint')`: it's to get all the features of the CLI without having to spawn subprocesses. A more complicated alternative would be to refactor out the non-`exit`-y parts of the CLI from `cli.js`.

**Comment by kokarn** [comment]
👍

**Comment by shellscape** [comment]
hm. when I take a look at other tools which have both a programmatic and cli interface, I can't come up with another one that supports calling the cli programmatically. gulp and grunt are two that come to mind. I'd be more inclined to work the essential bits into the main code from the cli, rather than open up and/or encourage programmatic use of the cli file. that just seems like an anti-pattern to me.

**Comment by JoshuaKGoldberg** [comment]
@shellscape agreed. I was being lazy. :)

https://github.com/palantir/tslint/pull/1688 is a similar construct.

**Comment by JoshuaKGoldberg** [comment]
Filed #283.

**Comment by JoshuaKGoldberg** [comment]
Fix would be in `lib/lesshint.js`:

```diff
     // Nothing defined, just fall back to our simple default
-    if (!reporter) {
+    if (!reporter || reporter === 'default') {
```
