### ISSUE TITLE
Allow reporters to be objects, not just file paths

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#282]
When running `lesshint` via `requires`/`imports` in code, instead of the CLI, it would be useful to pass a reporter object instead of a file path to one. This would allow for stateful reporters in tools that require `lesshint`.

The actual change would be pretty small, too - in `Lesshint.prototype.getReporter`, something like: 

```javascript
    // Object with .report as a method: return it directly
    if (reporter.constructor !== 'string' && 'report' in reporter) {
        return reporter;
    }
```

Required for https://github.com/lesshint/lesshint/issues/278.

**Comment by kokarn** [comment]
👍
