### ISSUE TITLE
Split the CLI into a new class

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#283]
As per https://github.com/lesshint/lesshint/issues/281, it would be useful to be able to call the CLI's logic via `require`/`import` rather than some form of subprocess.

Required for #278.

**Comment by jwilsson** [comment]
Makes sense, I guess. 

I'd be happy to help out/discuss design etc.

**Comment by JoshuaKGoldberg** [comment]
@jwilsson it looks like most of `cli.js` could just be moved into its own class in a new file.

Thinking of a name is hard. `runner.js`?
