### ISSUE TITLE
Some ideas for configLoader improvements

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#290]
I've got two ideas on how to improve the `configLoader`. I don't know if anyone knows that it will walk up to the root directory from `process.cwd()` until it finds a `.lesshintrc` when no config file is passed. This was never documented anywhere so the ideas I have for improvement are actually three :wink:

1. Add a second parameter, `path` which would tell it to start traversing somewhere else but defaulting to `process.cwd()` if `undefined`.
2. Create a new method `getConfig()` on the main `Lesshint` class which can be used by other tools (for example, we're hacky-loading the `configLoader` in our Gulp plugin right now. Similar to the current `getReporter()` method.
3. Document the fact that it traverses.

**Comment by kokarn** [comment]
👍
