### ISSUE TITLE
Enable Greenkeeper

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#295]
https://greenkeeper.io it's magical. added it to my repos yesterday and it already caught and submitted the dependency updates for a module. I've got it setup for postcss-values-parser. We should consider setting it up on the other org repos 😄

**Comment by kokarn** [comment]
It generates so much noise tho. 
Is is possible to just check and not open pull requests? 
Can't seem to find any information about that with a quick check.

**Comment by jwilsson** [comment]
I agree that it can get a bit noisy, but we already have pretty relaxed version constraints on our dependencies so it won't create PRs that often. 

If we enable it now it'll fail though, since the dependencies that are outdated doesn't support Node 0.12 (which we still do).

**Comment by kokarn** [comment]
👍 for dropping 0.12 and enabling greenkeeper

**Comment by jwilsson** [comment]
Greenkeeper enabled!

**Comment by shellscape** [comment]
woooo! 🎉
