### ISSUE TITLE
3.0 planning

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#297]
My plan is to merge #288 and #294 in the next few days, tag a `2.4.0`, and then start working through this list on `master`. I'm not thinking that this will be such a huge release as `2.0`, rather some small (but still breaking) changes and mostly focusing on stabilizing our public API.

- [x] Drop support for Node < 4.
- [x] `fullPath` in linting results should be an actual full path (now the path is just whatever's passed). I think this should be `path.resolve`d against `process.cwd()`.
- [x] Replace `vow` and `vow-fs` with native `Promise`s.
- [x] Implement #290.
- [x] Merge #285.
- [x] Merge ~~#289~~ #320 (new PR). I'd also like to write some proper docs on this since it's going to be used outside of `lesshint` I think it should be properly documented. ~~_(Pending a new PR based on discussions)_~~
- [x] Rewrite to ES6? I will have some time in a few weeks to work on this so I say we aim for a early 2017 release.

Any other thoughts or things I missed?

**Comment by shellscape** [comment]
Man, it's come such a long way!

**Comment by jwilsson** [comment]
@JoshuaKGoldberg I don't wanna stress you in any way but I just wanted to check if you're still interested in moving the CLI into a `runner.js`-file? Otherwise I'll be happy to do it 😄

**Comment by JoshuaKGoldberg** [comment]
Hi, yes - I was waiting for #307 to be resolved first. But if you do it first that would be great!

**Comment by jwilsson** [comment]
@JoshuaKGoldberg Oh, totally forgot about that one. Sorry! I'll take a look in the next couple of days.

**Comment by jwilsson** [comment]
A few things which came up still remains:
* Which parts of the API we expose, as discussed in #320. I'll file a PR for this.
* Finish #323.
* A patch for #321.
* @kokarn and I discussed some changes in the CLI Runner, he'll file a PR for it.
* Move the `lesshintFile` property on exceptions to its own custom `Error`. I'll file a PR for this.
* Finish up documentation improvements in the `doc-improvements` branch.

**Comment by justtal** [comment]
Hey Guys!

Your doing a great job here.

I would like to contribute to that project.

Is there any way to do that? Do you have a specific flow for new contributors?

Thanks,

Tal.

**Comment by jwilsson** [comment]
@justtal Thank you!

Take a quick look at [CONTRIBUTING.md](https://github.com/lesshint/lesshint/blob/master/CONTRIBUTING.md) and then grab one of the issues labeled [bug](https://github.com/lesshint/lesshint/issues?q=is%3Aissue+is%3Aopen+label%3Abug), I think those are the best for first-time contributions. Just to get a feel of the code.

If you have any questions, don't hesitate to ask!

**Comment by jwilsson** [comment]
And `3.0.0` has been released. A huge thank you to everyone who have contributed in any way!

**Comment by shellscape** [comment]
🎉

**Comment by JoshuaKGoldberg** [comment]
Whoohoo!

**Comment by kokarn** [comment]
🥇
