### ISSUE TITLE
Rule proposal: indent spaces

### ISSUE THREAD

**Issue by CASandmann** [lesshint/lesshint#298]
A rule to specify the number of spaces to indent.  Indention increases whenever a curly brace is opened and decreases whenever a curly brace is closed.

Suggested options:

* `style` - `spaces`, `tabs`
* `spacesPerIndent` - the number of spaces per indention if using spaces

If the style is spaces, then tabs will fail and vice-versa.

When style is `spaces` and `spacesPerIndent` is 2:

```
a {
  color: red;        // Passes
    border: none;    // Fails
}
```

**Comment by jwilsson** [comment]
This is the same as #50, right? We'd love some help on that one!

**Comment by CASandmann** [comment]
You're right.  I guess I didn't see it because it was so far down.  Just goes to show how important this type of rule is!  This issue can be closed.
