### ISSUE TITLE
Available options/default value for spaceBeforeBrace

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#3]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
1. no_space
2. one_space (**default**)
3. new_line

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
Can we get examples of how they look?

I assume it's like this?

no_space
```
div{
/* rules */
}
```

one_space
```
div {
/* rules */
}
```
new_line
```
div
{
/* rules */
}
```

**Comment by jwilsson** [comment]
Fixed in e5b0240a1b3b96d2b60bfba877c5240057e63461.

Any opinions on the default values/available options?

**Comment by kokarn** [comment]
Looks good!

No not really, maybe some people use tabs?

**Comment by kokarn** [comment]
Closing this as no other options that make sense have been presented.
