### ISSUE TITLE
Proposal: pass a logger object to CLI, reporters

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#300]
Spinning off of #289 - always using the global `console` object to log reports and errors means any constituents of a split-off runner class will have to stub out the standard process outputs.

Instead of:

```javascript
    report: function report (results) {
        console.log(JSON.stringify(results));
    }
```

it could now be:

```javascript
    report: function report (results, logger) {
        logger.log(JSON.stringify(results));
    }
```

The structural changes needed (post Runner-split) would be:
* `bin/lesshint` passes `console` to `lib/cli.js`
* `lib/cli.js` takes in a logger instead of directly using console and passes that to its Runner.
* `lib/runner.js::Runner` takes in a logger and passes it to its reporters.
* reporters are now given a logger object after errors that they can (should) use to log.

Using a provided logger gives the benefit that consumers of the reporters (such as our tests or external consumers of lesshint) don't need to globally mock or spy or stub the global console.

One downside is that existing custom linters won't be aware of the change, but since it's backwards compatible (doesn't change behavior for existing consumers) I don't think that should be a problem.

...and I'm of the belief that the term "dependency injection" does apply to this despite `console` being a global and not a framework-`new`ed instance :) but that definition does change per person.

**Comment by shellscape** [comment]
>  means any constituents of a split-off runner class will have to stub out the standard process outputs.

I'm having a hard time envisioning a situation where this would be necessary. I'd like to see a real-world example of the need here.

**Comment by JoshuaKGoldberg** [comment]
> real-world example of the need here.

[autolesshint](https://github.com/autolint/autolesshint). I want this to be a CLI app that people can just run like:

```
autolesshint --config ./lesshintrc
```

It'll run `lesshint` via `lesshint/lib/cli`, take in reports from the reporters, apply fixes, and repeat. #278.

**Comment by shellscape** [comment]
I looked through that but I couldn't immediately glean where you needed to stub console.log.

**Comment by JoshuaKGoldberg** [comment]
> stub console.log

By running the `lesshint` CLI is run via `lesshint/lib/cli` , it'll run the reporters, and those reporters will `console.log` their reports. 

Also, do you not find it inconvenient to do all the `.spy`/`.restore` calls in test code for `process.stderr/stdout.write` and `console.log/error`? IMO that's a general annoyance that could be fixed.

**Comment by JoshuaKGoldberg** [comment]
Ah, re-read my old code, and I see what you mean. In the current design you're right - it actually no longer needs to (it used to pipe output from a JSON reporter via the console, parse it as JSON, etc.).

Other potential use cases:
* Lightweight editor plugin 
* Browser previewer

**Comment by shellscape** [comment]
for other projects I work with we redirect stdout / console messages for other components in a number of spots. I'm of the opinion it's not really that unusual and not much of an inconvenience. (customizing gulp output, for example). As for the tests and the spies in the tests, I'd personally go with chai-spies over sinon, which would free up a lot of the annoyance of spying and restoring, but that's a separate discussion for another time. I don't think that a major change to a lib should be done to free up some lines in tests, however.

I'm not a big fan of this change, but I certainly won't block this addition on my opinion alone, simply weighing in for the rest of the team to consider.

**Comment by jwilsson** [comment]
Hmm, if `autolesshint` no longer needs it and we keep all logging in `lib/cli.js` (nothing in `lib/runner.js`) I don't see a need for it as this time.

If it's possible to introduce in a backwards compatible way (which it certainly looks like) then we can always add it later.
