### ISSUE TITLE
Allow a "everything is disabled" option for .lesshintrc files

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#309]
Writing `autolesshint` test cases is slightly more work than it should be because each `.lesshintrc` file needs to explicitly disable all the rules that are turned on by default. If any other rules get enabled by default as well, they'll need to be disabled too.

This also ties in to how my team at work is onboarding `lesshint` (very slowly). We had 0 rules enabled at first and by now just one. 

**Proposal**
How about a `"defaults"` object in the config files? Right now the only applicable "default" would be `enabled` (`true` by default).

`.lesshintrc`:
```json
{
    "defaults": {
        "enabled": false
    },
    "emptyRule": true
}
```

**Would you be interested in submitting a PR for this issue?**
Yes.

Miscellaneous: this does bring up a concern that putting assorted strings like `defaults` in the same object used to store rule settings could eventually start conflicting with rule names. Is this a concern?

**Comment by shellscape** [comment]
I'm torn on this proposal. On one hand, it looks like a great option for your tool. On the other hand, it looks like a good chunk of code to address an edge case. Playing devil's advocate here: An npm module containing the everything-is-disabled options hash/object could be published and you could require that module, and pass it to lesshint programatically.

**Comment by jwilsson** [comment]
I never thought about sharable configs for `lesshint`, but I like the idea. Perhaps that's something that's worth exploring more cause that sounds like something that might solve this problem for other people as well?

**Comment by shellscape** [comment]
@jwilsson I could put together an 'everything is disabled' module example

**Comment by jwilsson** [comment]
I'm gonna try to come up with something to add in the docs on how configs can be easily shared.

**Comment by JoshuaKGoldberg** [comment]
How about adding extensible configs à la [TSLint's `extends` option](https://github.com/palantir/tslint#configuration) to providing prefab ones? An everything-is-disabled option could be provided for this purpose.
