### ISSUE TITLE
Double \n characters give incorrect finalNewline positions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#310]
**Which version of `lesshint` are you using?**
2.4.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
Either CLI or Node.js API.

**What's your `.lesshintrc` configuration?**
`>node bin/lesshint --reporter lib/reporters/json temp/test.less`

**If you're reporting a bug, please show us some code that's failing.**
Contents of `temp/test.less`:
```less
.foo {}

.bar {}
```
To be precise, the string is `.foo {}\n\n.bar{}`

**What did you expect to happen?**
The JSON blob should report the position as 16 .

**What's the actual result?**
The position is reported as 22.

Note that the position gets correctly reported if a single `\n` is used (position 15) or `\r\n\r\n` is used (position 18).

**Would you be interested in submitting a PR for this issue?**
Yes.

**Comment by jwilsson** [comment]
@JoshuaKGoldberg Are you still interested in submitting a PR or should we label it as "Help wanted"?

**Comment by JoshuaKGoldberg** [comment]
Help wanted is probably best.

**Comment by JoshuaKGoldberg** [comment]
(just kidding, was messing around with regexps...)
