### ISSUE TITLE
Add "engines" to package.json

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#312]
Looks like .travis.yml is only testing on the latest node 4 version, so I wanted to run this by you guys before a PR. Is node 4@latest the minimum version lesshint supports now?

I ask because I'm ditching babel and ES6 modules in postcss-values-parser because babel has become a royal pain in the ass, and the modules syntax is the only thing I'm really using it for at this point. The next version of the module will be node 4@latest and up.

**Comment by jwilsson** [comment]
Yeah, we should add a `node >= 4`  field.
