### ISSUE TITLE
Max-Warnings Config Issue

### ISSUE THREAD

**Issue by Venomknight257** [lesshint/lesshint#321]
**Which version of `lesshint` are you using?** 2.4.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
CLI for testing. package.json run command in Node.js app

**What's your `.lesshintrc` configuration?** Default

**If you're reporting a bug, please show us some code that's failing.**
`lesshint --max-warnings=-1 ./path_to/styles/

**What did you expect to happen?**
I was expecting my build to succeed regardless of how many warnings I had.

**What's the actual result?**
I get an exit code of 1 and I received the following error when I ran the previous code:
`error: unknown options '-1'`

While I could use a positive integer for the time being, it would be nice to know what I am doing incorrectly to receive this error or for it to be corrected to work as expected.

**Comment by shellscape** [comment]
@jwilsson looks like it should work https://github.com/lesshint/lesshint/blob/afda593da9c5a3b0e27127757c29ccd75c5dda8d/lib/cli.js#L79 but there aren't any tests confirming that. looks like it may be a commander bug.

@Venomknight257 can you try with quotes around the `-1` and see what happens? eg. `lesshint --max-warnings="-1" ./path_to/styles/`

**Comment by Venomknight257** [comment]
I still get the same unknown option error when I add the quotes.

**Comment by Venomknight257** [comment]
I can attempt to make the changes for warnings to not break a build by default unless explicitly noted within the CLI or in config by the user and submit a PR.

**Comment by shellscape** [comment]
that might be an option, but would be a breaking change, so @jwilsson should weigh in on that one first

**Comment by Venomknight257** [comment]
From a quick glance it wouldn't be a sweeping change that I found to work... Now I haven't done extensive testing. 

Instead of having the `maxWarnings` flag having to be -1 why not have it be 0.

There can be an added check to see if the `max-warnings` flag was even given and if it wasn't then any warning will return an exit code of 1. If there was a flag specified and it was 0 then all warnings are ignore and return 0 otherwise it will return a code of 1 if warnings > maxWarnings(as it does now). 

It keeps the current functionality and fixes the "max-warnings" error issue.

I know @jwilsson should weigh in first on it and I await his comment(s) but I'm not thinking this will be as sweeping of a change as it may sound and won't break the current behavior in the process.

**Comment by jwilsson** [comment]
Hi @Venomknight257,
Thanks for the report!

I'm not too keen on changing any behaviour and it does indeed look like a [`commander.js` issue](https://github.com/tj/commander.js/issues/61). 

I would be fins with changing CLI parsing libraries ([meow](https://www.npmjs.com/package/meow) is the one that comes to mind) but it's a bit of work which I totally understand if you're not willing to do @Venomknight257. But if you wish to do it, we'd all be very happy 😄 

Just a few things to keep in mind for whoever's doing it:
* #320 needs to be merged first.
* I'm fine with changing the current `lib/cli.js` function signature.
* There might be quite a few test changes to be made.

I'm gonna take a look at some `bin/lesshint` tests as per #306 which will be helpful.

**Comment by shellscape** [comment]
We could parse the value for `false`, allowing folks to effectively disable that. some psuedo because 

```js
const maxWarnings;

if (isFinite(program.maxWarnings)) {
  maxWarnings = parseInt(program.maxWarnings, 10) || 0;
}
else {
  config.thing = new Boolean(program.maxWarnings);
}
```

**Comment by jwilsson** [comment]
That looks like it should work. I'm sorry if that's what you meant @Venomknight257. Would you be interested in submitting a PR with that fix?

**Comment by Venomknight257** [comment]
@shellscape That is actually a lot better than what I was thinking. I'll get a PR submitted with the fix and test updates.

**Comment by jwilsson** [comment]
@Venomknight257 Just wanted to check in with you. Is there anything we can help you with?

**Comment by Venomknight257** [comment]
Sorry guys. I've been outrageously busy with moving and prepping for my first kid that I haven't been able to dedicate as much time as I'd like to on this issue. I'll be on Paternity leave for two weeks starting next week and should be able to have plenty of time in the early mornings when I'm woken from a dead sleep from the newborn to get this written up. I wouldn't be offended if someone took it ran with it. As much as I'd like to contribute to this I'd much rather see the feature completed in time for the release than anything else.

Let me know if you still want me to finish this or if someone else wants to take it up while I juggle my time management with being a new dad.

**Comment by jwilsson** [comment]
@Venomknight257 I guess congratulations on the baby is in order then!

I filed a PR in #334 with the suggested changes, hope that's alright with you. I look forward to any future  future contributions from you!
