### ISSUE TITLE
New VariableOnly linter

### ISSUE THREAD

**Issue by justtal** [lesshint/lesshint#331]
I have created a new linter called "variableOnly" that validate that values of specific property is a variable.

At our team for color and font-size (for now) we use only variables that defined in app variables file.

Do you think it can be useful for other? do you want me to commit it to lesshint or create my own custom linter package?

You can pass to the linter the properties you want to be variable only:

```
"variableOnly": {
    "enabled": true,
    "properties": ['color', 'font-size']
}
```

Cheers,

Tal.

**Comment by jwilsson** [comment]
Sounds good to me!

Lets hear some other thoughts too, though.

**Comment by justtal** [comment]
Do you want me guys to commit it?

**Comment by shellscape** [comment]
I'd like to suggest a rename to `valueVariable`. Should consider future improvements to this and combinations of restraints of the property value using variables:

- always a variable
- never a variable
- (default would be disabled and unopinionated)

**Comment by jwilsson** [comment]
I'm fine with either name. A PR would be very much welcome!

**Comment by justtal** [comment]
@shellscape I really can't see a situation that someone will want the "never" option.

WDYT?
