### ISSUE TITLE
Mention autolesshint in the readme

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#339]
3.0 is out, so I've resumed work on [autolesshint](https://github.com/automutate/autolesshint/). You can install it and try it out; it should work! Unfortunately its current rule coverage probably isn't enough to justify putting a mention on the lesshint readme. A few issue points here...
* At what point (if any) would you be willing to mention it?
* What features do you want in it?
* The list of rules that need either have a suggestions generator written or be documented as un-suggestible is at its [Complete rule coverage](https://github.com/automutate/autolesshint/milestone/1) milestone. I'd greatly appreciate help filling those out!

**Comment by jwilsson** [comment]
> At what point (if any) would you be willing to mention it?

I would be willing to add it to our README pretty soon. Perhaps when support for a few more rules have been added.

> What features do you want in it?

Hmm, I'm not sure. I'm quite satisfied with just the autofixing parts. What did you have in mind?

> The list of rules that need either have a suggestions generator written or be documented as un-suggestible is at its Complete rule coverage milestone. I'd greatly appreciate help filling those out!

I'll see what I can do!

**Comment by JoshuaKGoldberg** [comment]
> a few more rules

These were actually a lot more straightforward (and fun!) to implement than I expected. It's up to 16 rules supported, 11 impossible to support, and 7 not-yet-implemented. I'll send a PR now.

> features in mind

I haven't the faintest idea. :)
