### ISSUE TITLE
Odd column numbers in space_after_property_value

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#344]
**Which version of `lesshint` are you using?**

3.0.1.

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**

Node.js API via `autolesshint`.

**What's your `.lesshintrc` configuration?**

```js
{
    // ... (all other rules are disabled)
    "spaceAfterPropertyValue": {
        "enabled": true,
        "style": "no_space" | "one_space"
    }
    // ...
}
```

**If you're reporting a bug, please show us some code that's failing.**

```less
.aaa {
    color: red;
           ^
}

.bbb {
    color: blue ;
            ^
}
```

**What did you expect to happen?**

When `style` is `"no_space"`, the error appears at line 6 / column 13. When `style` is `"one_space"`, the error appears at line 2 / column 12. See `^`s above.

**What's the actual result?**

Reported columns should be where the space is or isn't, no?

**Comment by jwilsson** [comment]
Strange, I'm getting these results (which I still agree are faulty):

`no_space`: line 6 / column 16
`one_space`: line 2 / column 15
