### ISSUE TITLE
Rule request: consecutive-blank-lines

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#347]
Prior art: http://eslint.org/docs/rules/no-multiple-empty-lines and https://palantir.github.io/tslint/rules/no-consecutive-blank-lines/.

This would be particularly useful for `autolesshint`. Right now the `single_line_per_*` rules just dump endlines as deemed necessary. In some situations that could end up with stylesheets that have a lot of consecutive blank lines.

**Comment by jwilsson** [comment]
I like it!

Let's see what the rest of the team think.

**Comment by justtal** [comment]
In my opinion and thanks to my OCD it is a must :)

**Comment by JoshuaKGoldberg** [comment]
Help would be great thanks; I've filed a lot of bugs lately and don't have much time to deal with them. :)

**Comment by jwilsson** [comment]
@justtal I say go for it!
