### ISSUE TITLE
Prefixing URL setting with Variable

### ISSUE THREAD

**Issue by elliottcrush** [lesshint/lesshint#354]
What does everyone think about introducing a custom rule to allow for the ability to always expect a URL assignment to be prefixed by a given variable.

**Invalid**
```
background: url('/somedomain.com/assets/images/example.png');
```
**Valid**
```
background: url('@{assets-cdn}/example.png');
```

I want the ability to control where assets are sourced from in my applications and this seems like a useful rule to me. 

**Which version of `lesshint` are you using?**
Latest

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
Gulp 

**What's your `.lesshintrc` configuration?**
```js
{
  "fileExtensions": [".less", ".css"],

  "excludedFiles": ["vendor.less"],

  "attributeQuotes": false,
  "borderZero": {
    "style": "zero"
  },
  "decimalZero": {
    "style": "none"
  },
  "depthLevel": true,
  "duplicateProperty": {
    "exclude": ["display", "background-image", "background-color", "src"] // Fallbacks
  },
  "finalNewline": true,
  "hexLength": false,
  "hexNotation": {
    "style": "lowercase"
  },
  "hexValidation": true,
  "idSelector": {
    "exclude": ["#gradient", "#nav-affix"]
  },
  "importantRule": false,
  "importPath": {
    "filenameExtension": false,
    "leadingUnderscore": false,
    "exclude": []
  },
  "maxCharPerLine": false,
  "newlineAfterBlock": false,
  "propertyOrdering": false,
  "propertyUnits": {
    "valid": ["px", "em", "rem"],
    "invalid": ["pt", "rem", "vw", "vh"]
  },
  "qualifyingElement": {
    "allowWithAttribute": true,
    "allowWithClass": true, // Controversial
    "allowWithId": false
  },
  "selectorNaming": {
    "disallowUppercase": true,
    "disallowDash": false,
    "disallowUnderscore": true // May need to allow for SB mapping
  },
  "singleLinePerProperty": {
    "allowSingleLineRules": true
  },
  "singleLinePerSelector": {
    "style": "18f"
  },
  "spaceAfterPropertyColon": false,
  "spaceAfterPropertyName": {
    "style": "no_space"
  },
  "spaceAfterPropertyValue": {
    "style": "no_space"
  },
  "spaceAroundComma": {
    "allowNewline": false,
    "style": "after"
  },
  "spaceAroundOperator": false,
  "spaceBeforeBrace": {
    "style": "one_space"
  },
  "spaceBetweenParens": {
    "style": "no_space"
  },
  "stringQuotes": {
    "style": "single"
  },
  "trailingSemicolon": true,
  "trailingWhitespace": true,
  "urlFormat": {
    "style": "relative"
  },
  "universalSelector": false,
  "urlQuotes": false,
  "variableValue": {
   "always": ["color", "font-size"] // Would like to add margin and padding here but resetting would be hard
  },
  "zeroUnit": {
    "style": "no_unit"
  }
}
```

**If you're reporting a bug, please show us some code that's failing.**

```less
// Code here
```

**What did you expect to happen?**

**What's the actual result?**

**Would you be interested in submitting a PR for this issue?**
Definitely

**Comment by kokarn** [comment]
Cool idea, I like it.

I don't really see a reason not to add it, but I'll let the others decide.

**Comment by h0rhay** [comment]
👍 Thumbs up from me, this would be a great feature.

**Comment by jwilsson** [comment]
@elliottcrush Thanks for the well-written proposal and for using the template!

I'm not sure this is a fit for core though. I could see it conflicting with `urlFormat` and doesn't feel general-purpose enough. But it sounds like a great fit for a [custom linter](https://github.com/lesshint/lesshint/blob/master/docs/developer-guide/linters.md).

I've been thinking about adding a list of community rules and would be happy to include this one there if you decide to create it and release it in the open.

**Comment by kokarn** [comment]
@jwilsson a custom linter seems a bit overkill, doesn't it? Or do I confuse linters with rules in a more general sense?

I can agree that it doesn't seem general-purpose enough but having a way to add custom rules easy seems like something that might be a good idea.

**Comment by elliottcrush** [comment]
I wonder if the naming i've chosen above is perhaps not as clear as it should be @jwilsson 

Perhaps the ability to pass in an array of variables you'd wish to prefix with would also be beneficial and more it more general purpose. 

```
  "prefixUrlWithVariable": {
    "enabled": true,
    "allowed": ["company-cdn", "bootstrap-cdn"]
  },
```

Perhaps if that is still an uncomfortable change I could extend the `urlFormat` method to support known variables as a prefix to a URL?

**Comment by shellscape** [comment]
It's a neat idea for sure, but this is too specialized for lesshint core imho. We've talked about third party, add-on linters in the past, and I think this is a great fit for that. It's also a great fit for a webpack (or your packer of choice) plugin.

**Comment by jwilsson** [comment]
@kokarn Yes, custom rules and custom linters are the same. I'm just sloppy and use the terms interchangeably.

I'm sorry, @elliottcrush. I still think it's too specialized. But as stated earlier, we'd be happy to provide a link to it in our docs.

**Comment by elliottcrush** [comment]
Thanks @shellscape, @jwilsson and @kokarn - I understand that its not a fit for core. I'll separate it into a customer linter and notify you all when its all setup. Thanks for the feedback
