### ISSUE TITLE
Value Exclusions for VariableValue rule.

### ISSUE THREAD

**Issue by jodiedoubleday** [lesshint/lesshint#355]
**Which version of `lesshint` are you using?**
Latest

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
Gulp

**What's your `.lesshintrc` configuration?**

```js
{
  "fileExtensions": [".less", ".css"],

  "excludedFiles": ["vendor.less"],

  "attributeQuotes": false,
  "borderZero": {
    "style": "zero"
  },
  "decimalZero": {
    "style": "none"
  },
  "depthLevel": true,
  "duplicateProperty": {
    "exclude": ["display", "background-image", "background-color", "src"] // Fallbacks
  },
  "finalNewline": true,
  "hexLength": false,
  "hexNotation": {
    "style": "lowercase"
  },
  "hexValidation": true,
  "idSelector": {
    "exclude": ["#gradient", "#nav-affix"]
  },
  "importantRule": false,
  "importPath": {
    "filenameExtension": false,
    "leadingUnderscore": false,
    "exclude": []
  },
  "maxCharPerLine": false,
  "newlineAfterBlock": false,
  "propertyOrdering": false,
  "propertyUnits": {
    "valid": ["px", "em", "rem"],
    "invalid": ["pt", "rem", "vw", "vh"]
  },
  "qualifyingElement": {
    "allowWithAttribute": true,
    "allowWithClass": true, // Controversial
    "allowWithId": false
  },
  "selectorNaming": {
    "disallowUppercase": true,
    "disallowDash": false,
    "disallowUnderscore": true // May need to allow for SB mapping
  },
  "singleLinePerProperty": {
    "allowSingleLineRules": true
  },
  "singleLinePerSelector": {
    "style": "18f"
  },
  "spaceAfterPropertyColon": false,
  "spaceAfterPropertyName": {
    "style": "no_space"
  },
  "spaceAfterPropertyValue": {
    "style": "no_space"
  },
  "spaceAroundComma": {
    "allowNewline": false,
    "style": "after"
  },
  "spaceAroundOperator": false,
  "spaceBeforeBrace": {
    "style": "one_space"
  },
  "spaceBetweenParens": {
    "style": "no_space"
  },
  "stringQuotes": {
    "style": "single"
  },
  "trailingSemicolon": true,
  "trailingWhitespace": true,
  "urlFormat": {
    "style": "relative"
  },
  "universalSelector": false,
  "urlQuotes": false,
  "variableValue": {
   "always": ["color", "font-size"]
  },
  "zeroUnit": {
    "style": "no_unit"
  }
}
```

**What did you expect to happen?**

You can list values which are accepted that don't have to be variables.
Variables are great for consistency, but in the example of `color` having to be variables, `inherit` fails. I don't think it's correct to have to create and inherit variable.
``` js
  "variableValue": {
   "always": ["color", "font-size"],
   "exclude": ["inherit", "none"]
  },
```

## Invalid
``` js
.foo {
  color: #09F;
}
```

## Valid
``` js
.foo {
  color: @blue;
}
```

## Valid (with inherit exclusion)
``` js
.foo {
  color: inherit;
}
```

**Would you be interested in submitting a PR for this issue?**
I could give it a go, if you guys agree it's worthwhile

**Comment by shellscape** [comment]
I think the issue formatting got a little hosed. I'm not quite sure what is invalid and valid. And it looks like your `exclude` property in the "expected" section isn't using quotes.

Is this issue reporting a problem, or are you proposing a new feature?

**Comment by jodiedoubleday** [comment]
Apologies for that, formatting is now fixed :)

**Comment by kokarn** [comment]
I'm not following 100% either.

You want to specify a property that has to have a variable as a value but you want to treat some values, such as ```none``` and ```inherit``` as a variable, correct?

**Comment by jodiedoubleday** [comment]
So in my config i have `VariableValue` switched on for `color`
I want to ensure people use colors from a specified color palette which have already been created as variables previously. So i'm forcing people to use variables.

However, sometimes people might want to use `color: inherit` which is a legit. The aren't creating new colors, but i don't feel like inherit needs to be a variable.

essentially allow some values as "okay not be be variables"

**Comment by kokarn** [comment]
👍 Sounds good, any other members wanna chime in?

**Comment by shellscape** [comment]
Seems like a good use case to me. My vote is for an `allowedValues` property to specify which values are also allowed.

This then begs the question - should we nix `valueVariable` and move that into a linter which specifies what types of values can be applied to a property?

**Comment by jwilsson** [comment]
I think we should go for a `exclude`/`allowedValues` option (not sure about the name yet) but a PR would be more than welcome @jodiedoubleday!
