### ISSUE TITLE
can not run lint by powershell

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [lesshint/lesshint#356]
I tried to run command "node .\node_modules\lesshint\bin\lesshint  .\Content\**\*.less" on powershell (windows10). Nothing crashed but i didn't get any output. 

Command " node ./node_modules/lesshint/bin/lesshint ./src/Radar.API/Content/**/*.less" run on windows10 bash generate correct output.

Any suggestions how I can run lesshint from powershell?

**Comment by shellscape** [comment]
@JoshuaKGoldberg was it you that was running this on winders? I can't recall. I haven't used windows for day to day stuff since 2010, and that pre-powershell heyday, so I'm not going to be much help with this one.

it does seem odd that you need to specify the full path to lesshint. Why isn't lesshint available as a standalone command after using `npm install -g lesshint`? Seems strange.

**Comment by kokarn** [comment]
I'm running windows. I'll have a look ASAP, hopefully today

**Comment by kokarn** [comment]
Quick check.

I've installed lesshint globally with ```npm install -g lesshint``` in a default terminal.

Running ```lesshint test.less``` works as expected inside powershell for me.

**Comment by przemyslawjanpietrzak** [comment]
Command `lesshint file.less` works in powershell.
But I can't run command for lint all less files.
Install lesshint globally doesn't change anything.

**Comment by kokarn** [comment]
I assume you did what I tried and ran ```lesshint *.less```? 
You have to specify a file and/or folder, not a glob pattern.

If not, what command did you run?

**Comment by przemyslawjanpietrzak** [comment]
Commands `lesshint .` or `lesshint *.less` doesn't print any output.
Lint exact file works correctly.

**Comment by kokarn** [comment]
Can you send the file?

I've tested ```lesshint .``` in my powershell and that works fine

**Comment by przemyslawjanpietrzak** [comment]
I can not (company policy), sorry.

I noticed that command `lesshint .` takes couple seconds. After that returns 0, without any print.
So linter should works correctly, but generate output doesn't not (on my machine).

**Comment by kokarn** [comment]
Can you maybe build a custom file that represents the error that you can share with us?

Please try with this file and see if that works
```
div.test {
    color: green;
}
```
Is every file in the same folder?
What Windows version are you on?

**Comment by przemyslawjanpietrzak** [comment]
Command `less style.less` (this this content) prints 
```Warning: style.less: line 1, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Warning: style.less: line 3, col 2, finalNewline: Files should end with a newline.```

All less files are in the same main folder, but can be in different sub-folders.
I'm using Windows 10 Pro.
Lesshint version === 3.1.0.

**Comment by kokarn** [comment]
I'm sorry, but I can't reproduce at all. Not sure what to do at this point :/
![screenshot](http://i.imgur.com/URL1fix.png)

**Comment by przemyslawjanpietrzak** [comment]
So it's something wrong with my OS.
Thank you for your time :)

**Comment by kokarn** [comment]
I'll leave this open for a week or something to see if somebody has any ideas. If not I think we can close.

**Comment by JoshuaKGoldberg** [comment]
@przemyslawjanpietrzak have you tried running it via the traditional cmd instead of powershell? Does that work?

We should try to eliminate the possibility of it being a `lesshint` bug. There are at least a couple things you can try:
* Can you binary search the offending `.less` file?
  * Remove the first half of the file
  * Re-run `lesshint` on the file
  * If it gives output, leave out the first half; if not, put it back and remove the second half
  * Repeat until you find a line that produces no output
* Put a whole bunch of `console.log("Yippee!", arguments);` in your `lesshint`
  * Find it with `where lesshint` - it should be in some `AppData`-ish directory if installed globally, or `node_modules` if locally to a project

**Comment by kokarn** [comment]
Just a quick note, as far as I understood it works in bash but not powershell

> I tried to run command "node .\node_modules\lesshint\bin\lesshint .\Content***.less" on powershell (windows10). Nothing crashed but i didn't get any output.
> 
> Command " node ./node_modules/lesshint/bin/lesshint ./src/Radar.API/Content/**/*.less" run on windows10 bash generate correct output.

**Comment by przemyslawjanpietrzak** [comment]
I debug lesshint and during run lint with arg `.\**\*.less` from powershell, runner.js file catch  `Error: ENOENT: no such file or directory, stat 'Q:\lesshint\**\*.less`. Error came from `fs.stat(checkPath, (err, stats)...` call in lib/lesshint.js file

**Comment by JoshuaKGoldberg** [comment]
> it works in bash but not powershell

Is this referring to the Ubuntu bash on Windows 10, which is actually bash, or the default Windows command prompt?

A few comments on your post:
* Why the `/` verses `\` difference in slashes? Do things change if you use the same style in both cmd and powershell?
* A little more error information than the `ENOENT` would be nice. Can you `console.log(new Error().stack);`? What are the paths your `lesshint` is located at, you're running from, and the file is located at?
* Could you make a copy of the file, replace all company secrets with foo-bar/lorem-ipsum nonsense, and upload it here?

**Comment by przemyslawjanpietrzak** [comment]
1) `/` is just for bash, cmd and powershell required `\` 
2) full error message 
```
{ Error: ENOENT: no such file or directory, stat 'Q:\lesshint\**\*.less'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'Q:\\lesshint\\**\\*.less' }
```
I located `lesshint` in node_modules, globally, or from cloned repo effect still the same.

3) I can, but `lesshint` crashed before any file is read (lib/lesshint.js: line 91 fs.stat error)

**Comment by jwilsson** [comment]
I know this is waaaay to late, but in case someone else stumbles upon this issue.

In `lesshint@4.5.0` the CLI has a new method to check globs. Try running the `lesshint` command and quoting your glob pattern, i.e:

```sh
lesshint "*.less"
``` 

This will ensure the glob pattern is passed straight through to `lesshint`.
