### ISSUE TITLE
Available options/default value for propertyUnits

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#36]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
global: [] Array of allowed units (currently all CSS units)
properties: {} Object with unit overrides for specific properties

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
I'd like a global exclude option actually, maybe a exclude list for properties as well.

The usecase for that is we only currently dislike the vh unit because of it's crappy behaviour on mobile, everything else is good.

That way it's forwards compatible as well.

**Comment by CITguy** [comment]
I like the idea of having two ways to configure the units (whitelisting vs blacklisting).
Maybe change the config to be something like this...

```javascript
/* BLACKLISTING */
"propertyUnits": {
  "permit": "deny",
  "units": ["rem", "vh"], // these units will not be allowed anywhere
  // property-specific units
  "properties": {
    "min-height": ["vh"] // vh will be allowed in addition to globally allowed units
  }
}

/* WHITELISTING */
"propertyUnits": {
  "permit": "allow",
  "units": ["px", "%"], // only these units will be allowed
  // property-specific units
  "properties": {
    "min-height": ["vh"] // vh will be allowed in addition to globally allowed units
  }
}
```

The majority of the configuration will take place with the `permit` and `units` values. The `properties` option will only be used to handle the edge cases.

**Comment by kokarn** [comment]
That's great and gives a lot of flexibility. :+1:

**Comment by jwilsson** [comment]
@CITguy I really like the idea but I feel this has been sitting for a while and I don't think I will have the time in the near future to implement it. Do you have the time?

**Comment by shellscape** [comment]
I think the `permit` based approach is too superfluous. Here's my proposal:

```
"propertyUnits": {
  "valid": ["px", "%"], // only these units will be allowed
  "invalid": ["em"], // not allowed under any circumstance

  "properties": {
    "min-height": ["vh"] // vh will be allowed in addition to 'valid' units
  }
}
```

**Comment by kokarn** [comment]
This is now solved thanks to @shellscape
