### ISSUE TITLE
Config file not found in project root, instead looking in node_modules folder

### ISSUE THREAD

**Issue by lucastobrazil** [lesshint/lesshint#369]
**Which version of `lesshint` are you using?**
Using Lesshint 3.1.1 

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
via npm start - lesshint is being run via lesshint-webpack-plugin

**If you're reporting a bug, please show us some code that's failing.**
```
module.exports = function (path) {
    path = path || process.cwd();
    const stats = fs.statSync(path);
    let config;

    if (stats.isFile()) {
        // A file was passed, try to load it
        config = loadConfig(path);
    } else {
        // Try to find a config file instead
        const rcfinder = new RcFinder('.lesshintrc', {
            loader: loadConfig
        });

        config = rcfinder.find(path);
    }

    return config;
};
```

**What did you expect to happen?**
I am running `webpack` from a `webpack.config.js` file and using the `lesshint-webpack-plugin` in my plugins. From the documentation, lesshint should look for a `.lesshintrc` file in my project root (ie. same folder as the webpack config file), however it does not see my .lesshintrc file.

When debugging the `config-loader.js` file of lesshint, I noticed that the process.cwd() seems to return the lesshint plugin in the `node_modules` directory, instead of the top level project root folder, thus it cannot find my .lesshintrc file and just uses the default.

is this a bug or working properly? i don't mind setting the path to a .json file instead, however i thought it's supposed to just look for my file directly, and documentation seemed to suggest that that's how it should work.

Thanks guys :)

**Comment by jwilsson** [comment]
Hi!
It should work like you expect it to, what does your `npm start` script look like?

**Comment by lucastobrazil** [comment]
```
// package.json
"scripts": {
    "dev:webpack": "webpack-dev-server --inline --hot",
    "start": "run-p dev:*"
  },
```

**Comment by lucastobrazil** [comment]
```
// webpack.config.js
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const LessHintPlugin = require('lesshint-webpack-plugin');

module.exports = {
	entry: {
		'my-app': './src/index.js',
		'vendor': [
			'lodash',
			'react',
			'react-dom'
		]
	},
	output: {
		path: path.resolve('dist'),
		filename: '[name].js',
		publicPath: '/'
	},
	resolve: {
		modules: [
			path.resolve(__dirname, './src/'),
			'node_modules'
		],
		alias: {
			images: path.resolve(__dirname, './src/img/'),
		}
	},
	module: {
		rules: [{
				enforce: 'pre',
				test: /\.js$/,
				exclude: /node_modules/,
				loader: 'eslint-loader',
			},
			{
				test: /\.js$/,
				loaders: ['react-hot-loader/webpack', 'babel-loader'],
				exclude: /node_modules/
			},
			{
				test: /\.(jpe?g|gif|png|svg|woff|ttf|wav|mp3)$/,
				use: [{
					loader: 'file-loader',
					options: {
						name: '[path][hash].[ext]'
					}
				}]
			},
			{
				test: /\.css$/,
				use: [
					'style-loader',
					{
						loader: 'css-loader',
						options: {
							importLoaders: 1,
							modules: true,
							localIdentName: '[folder]-[local]-[hash:base64:5]'
						}
					},
					{
						loader: 'postcss-loader',
						options: {
							plugins: [
								require('postcss-import')({
									path: './src'
								}),
								require('postcss-cssnext')()
							]
						}
					}
				]
			}
		]
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: './src/index.html',
			filename: 'index.html',
			inject: 'body'
		}),
		new webpack.optimize.CommonsChunkPlugin({
			name: 'vendor',
			filename: '[name].[hash].js',
			minChunks: Infinity
		}),
		new webpack.NamedModulesPlugin(),
		new LessHintPlugin({
			files: [
				'./src/**/*.css'
			],
			reporter: require('lesshint-reporter-stylisher'),
			// configFile: path.resolve(__dirname, '.lesshintrc')
		})
	]
}
```

**Comment by jwilsson** [comment]
Hmm, this is really strange. It's picking up the `.lesshintrc` file for me. Which OS are you on?

**Comment by lucastobrazil** [comment]
Mac OS Sierra 10.12.3. Here's the repo i'm working on if you want to clone it and see :)
https://github.com/lucastobrazil/MyReactBoilerplate

**Comment by jwilsson** [comment]
Cool, thanks! We're on the same OS then, so that's not the problem.

I tried with that repo too and I'm getting linting errors:

```
/Users/jwilsson/MyReactBoilerplate/src/components/Button/style.css
  13:2  warning  Property ordering is not alphabetized  propertyOrdering
```

I don't know what to tell you 😕  But if you're fine with passing a JSON-file then I guess that's the solution for now. Let me know if you find the issue, though!

**Comment by lucastobrazil** [comment]
Sure thing :) yep that warning is there on purpose - basically my _actual_ '.lesshintrc' file has this property turned off, so if the plugin were reading from my file then it wouldn't throw that warning. 

All good though! Just odd behaviour eh! Will let u know if I find the culprit :-)

**Comment by jwilsson** [comment]
Ah, sorry! My bad, I didn't look closely enough.

But! I think I found the issue, the `lesshint-webpack-plugin` doesn't use the [Lesshint.getConfig()](https://github.com/lesshint/lesshint/blob/master/docs/developer-guide/api/lesshint.md#lesshintgetconfigpath) method to load the config file. That's the method which is responsible for looking for a `.lesshintrc` file.

I'd file an issue on the `lesshint-webpack-plugin` repo. Or, better yet, send them a PR utilizing that method 😀

**Comment by lucastobrazil** [comment]
Ahh nice! thanks :) Will do.

**Comment by shellscape** [comment]
@jwilsson we ought to invite the project into the org :)

**Comment by jwilsson** [comment]
@shellscape Good idea! I'll reach out to them.
