### ISSUE TITLE
postcss-less Project Adoption

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#380]
Well, it's official - The [postcss-less](https://github.com/webschik/postcss-less) project has been tagged on the first line of its README as "UNMAINTAINED." I've reached out to @webschik to see if there's any chance of transferring ownership of the repo and npm module.

The situation begs two questions:
- Is the org interested in maintaining that module?
- Are we willing to devote time to the module?
- Do we write our own?

**Comment by shellscape** [comment]
So some good news, the owner transferred the project over this evening. I merged a PR for PostCSS 5.2 support. What are the outstanding issues preventing us from updating at this point?

**Comment by jwilsson** [comment]
That's great news! 🎉  

I'll admit I was a bit reluctant to keep it under the lesshint org, it could have sent the wrong signals, i.e. that we cater to our needs first and foremost (which I don't think we should) and that would've kept people from using it.

I'm glad it worked out this way and so fast too! I'll of course help out as much as I can.

I just took it for a test run with the latest master (https://github.com/shellscape/postcss-less/commit/0484694000a8d936a3b751afb37658aede5e5f7d) and all tests pass! So right now we don't have anything stopping us from tagging a new version and using that while we iron out the other open issues.

**Comment by jwilsson** [comment]
Closing this since it's been adopted by you, @shellscape.

**Comment by shellscape** [comment]
Ah yes, sorry for the lack of update. Had a great convo with webschik and he transferred it over.
