### ISSUE TITLE
Bumping the Engine to Node 6x

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#381]
(Copied from my comment on https://github.com/stylelint/stylelint/pull/2497 - I think this is valid for Lesshint as well)

there's a myriad of functional, language, and performance updates that benefit users of newer versions of node, as can be seen here: http://node.green/. Node v4 was first released in 2015. Not wanting to exclude users that cannot update is noble, but those users have to grapple with projects moving onto to new versions. Bumping the engine to v6 can be a major version change, which won't affect those users stuck in 2015 😄

I'm looking at moving postcss-less to a 6x engine setting to take advantage of the language improvements, which might affect Lesshint. Thoughts?

**Comment by jwilsson** [comment]
Hmm, since Node 4 is still supported by the Node Foundation for almost a whole year more (albeit in maintenance mode) I don't really feel comfortable dropping support for it just yet.

While I'm not really a fan of transpiling Node modules perhaps that could be a solution? Using something like [babel-env](https://github.com/babel/babel-preset-env) to just target Node 4 in `postcss-less` we won't need to transpile as much either. How do you feel about that?

**Comment by shellscape** [comment]
Well I (and the company I work for) go off of the LTS timeline. Active LTS ended on April 1st and maintenance mode is really nothing more than "your last chance before we ditch the version." Node 4 is two years old, and in technology that's a millennium. Adding that people have had a full year to update to something other than 4, and I'm sold on the engine bump. We're a component, a small tool, and while I do think it's noble to want to cater to the unfortunate, the component is being held back significantly by it.

Most of my stuff is on Node 7.6 already, which hasn't even entered LTS, planning ahead for the impending Node 8 release, which is gonna be bananas cool. With postcss-less and postcss-values-parser, I'll probably release one more version on Node 4 with the transpiling intact, and the following major version will remove all of that to take advantage of the improvements in Node 6.

**Comment by kokarn** [comment]
I'm with @jwilsson on this. 
We have a lot of systems and developers still running node 4 in a bunch of different scenarios and I don't really see the great benefit of dropping it. 

Sure we could write it to be more performant and run some newer, cooler features but what do we actually gain from it?

**Comment by jwilsson** [comment]
I'm totally fine with `postcss-less` and `postcss-values-parser` moving on (just tag major versions, please 😬 ) but I think we should keep `lesshint` on Node 4 for now.

**Comment by shellscape** [comment]
> Sure we could write it to be more performant 

that. you gain that right there. lol. build process time is precious.

**Comment by kokarn** [comment]
I totally agree that we still have 4.* in some places is absolutely a problem. But as large corporations go, that's usually where it ends up. We do have upgrade paths but it's not prioritised as long as 4 is supported.

Regarding 0.12 we dropped it less than 6 months ago, almost exactly at the same time maintenance stopped. I think we should do the same for 4.*

**Comment by shellscape** [comment]
Welp, that's unfortunate. New versions of Lesshint really should be moved to a newer minimum version of node to take advantage of the massive performance improvements 6x enjoys. The decision not to essentially punishes the majority of your users while supporting the unfortunate few.

**Comment by shellscape** [comment]
And just so you guys know I'm not being silly about the incredible improvements in Node 6...

http://www.infoworld.com/article/3061213/javascript/nodejs-6-taps-v8-update-for-more-speed-security.html
https://blog.risingstack.com/whats-new-in-node-v6/
https://blog.wikimedia.org/2017/02/17/node-6-wikimedia/

The info in those articles alone should be influential.

**Comment by jwilsson** [comment]
Thanks for the links!

But based on those and other things I've read and heard, I've gotten the impression that most performance improvements are related to changes in V8 and Node internals. So users on Node 6 will get the improvements anyway, right? While those on Node 4 simply won't.

I agree that there are some really nice features in ES2016, ES2017, and so forth but I don't see anything obvious in `lesshint` where we could rewrite something using newer features which would yield a huge performance improvement.
