### ISSUE TITLE
Proactive: postcss-less 1.0 and Imports

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#384]
[ A quick issue to track a coming breaking change to postcss-less 1.0 in a week or three. see [postcss-less:#56](https://github.com/shellscape/postcss-less/issues/57) ]

In prior versions, imports were handled as `AtRule` and some of the LESS-specific things about `@import` like directives were misplaced in properties for `AtRule`. As of 1.0, a new node type `Import` will replace `AtRule` for `@import`.

Example:

```less
@import (inline) "foo.less";
```

Produces:

```js
Import {
  raws: { before: '', between: '', afterName: '' },
  type: 'import',
  nodes: [],
  name: 'import',
  parent: 
   Root {
     raws: { semicolon: false, after: '' },
     type: 'root',
     nodes: [ [Circular] ],
     source: { input: [Object], start: [Object] } },
  source: 
   { start: { line: 1, column: 1 },
     input: Input { css: '@import (inline) "foo.less";', id: '<input css 1>' },
     end: { line: 1, column: 28 } },
  importPath: '"foo.less"',
  directives: '(inline)' }
```

Note the new `directives` and `importPath` properties. That should allow for much easier parsing and comparison.

**Comment by jwilsson** [comment]
Great, thanks for the heads up!
