### ISSUE TITLE
Documentation about inline configuration isn't clear

### ISSUE THREAD

**Issue by kaiyoma** [lesshint/lesshint#385]
In particular, this section: https://github.com/lesshint/lesshint/blob/master/docs/user-guide/configuration.md#inline-configuration

It fails to mention that the `// lesshint foo` line must be the first line in the file. I wasted a lot of time today trying to figure out why my ignores weren't working. I noticed there's a proposal to make these ignore statements more flexible, but until then, the docs should be updated to reflect the current state of things.

**Comment by jwilsson** [comment]
Agreed, I'll look at updating it.
