### ISSUE TITLE
CLI output of path-less filenames is ambiguous

### ISSUE THREAD

**Issue by kaiyoma** [lesshint/lesshint#386]
We have lots of `styles.less` files scattered throughout our project (over 60 at last count). When I run lesshint, I get output that looks like this:

```
Warning: styles.less: line 48, col 3, propertyOrdering: Property ordering is not alphabetized
Warning: styles.less: line 5, col 3, propertyOrdering: Property ordering is not alphabetized
Warning: styles.less: line 7, col 3, propertyOrdering: Property ordering is not alphabetized
Warning: styles.less: line 7, col 3, propertyOrdering: Property ordering is not alphabetized
Warning: styles.less: line 52, col 3, propertyOrdering: Property ordering is not alphabetized
```

Clearly, this isn't helpful at all. I admit that always printing the full path could be really noisy and annoying, but maybe we could have a command-line option for printing the full path?

**Comment by jwilsson** [comment]
Could another reporter work? For example [lesshint-reporter-stylisher](https://www.npmjs.com/package/lesshint-reporter-stylisher)?

**Comment by kaiyoma** [comment]
Oh interesting, I didn't know about that. Let me try it out tomorrow and get back to you.

**Comment by wareczek** [comment]
reporter-teamcity has file paths, but you need to use it with TeamCity :)
https://github.com/lesshint/reporter-teamcity


![screenshot from 2017-05-11 15-17-21](https://cloud.githubusercontent.com/assets/1897839/25951115/01d50c32-365d-11e7-8fe5-4617b6d31071.png)

**Comment by kaiyoma** [comment]
@jwilsson The "stylisher" reporter is just what I was looking for, thanks! Feel free to close this issue.
