### ISSUE TITLE
Variables in class names picked up as qualifying elements

### ISSUE THREAD

**Issue by JakeSidSmith** [lesshint/lesshint#391]
**Which version of `lesshint` are you using?**

`3.3.1`

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**

CLI:

`lesshint 'src/less/'`

**What's your `.lesshintrc` configuration?**

Only part that's relevant:

```json
  "qualifyingElement": {
    "enabled": true,
    "severity": "error",
    "allowWithAttribute": false,
    "allowWithClass": false,
    "allowWithId": false
  },
```

**If you're reporting a bug, please show us some code that's failing.**

```less
.generate-columns (@prefix, @counter: 1) when (@counter < @grid-divisions) {
  &.@{prefix}-@{counter} {
    width: floor(percentage(1 / @grid-divisions * @counter) * 100) / 100;
  }

  &.@{prefix}-offset-@{counter} {
    margin-left: floor(percentage(1 / @grid-divisions * @counter) * 100) / 100;
  }

  &.@{prefix}-fill-@{counter} {
    margin-right: floor(percentage(1 / @grid-divisions * @counter) * 100) / 100;
  }

  &.@{prefix}-push-@{counter} {
    left: floor(percentage(1 / @grid-divisions * @counter) * 100) / 100;
  }

  &.@{prefix}-pull-@{counter} {
    left: floor(percentage(1 / @grid-divisions * @counter) * 100) / 100 * -1;
  }

  .generate-columns(@prefix, @counter + 1);
}

.column {
  .generate-columns(xs);

  @media all and (min-width: @screen-sm) {
    .generate-columns(sm);
  }

  @media all and (min-width: @screen-md) {
    .generate-columns(md);
  }

  @media all and (min-width: @screen-lg) {
    .generate-columns(lg);
  }

  @media all and (min-width: @screen-xl) {
    .generate-columns(xl);
  }
}
```

**What did you expect to happen?**

These lines should not error

**What's the actual result?**

Appears to pick up variables in class names as qualifying elements. As a side note, it also appears to print the errors twice, but this may be for the different sub-rules e.g. `allowWithAttribute: false` and `allowWithClass: false`.

```shell
Error: grid.less: line 4, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Error: grid.less: line 4, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Error: grid.less: line 8, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Error: grid.less: line 8, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Error: grid.less: line 12, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Error: grid.less: line 12, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Error: grid.less: line 16, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Error: grid.less: line 16, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Error: grid.less: line 20, col 4, qualifyingElement: Class selectors should not include a qualifying element.
Error: grid.less: line 20, col 4, qualifyingElement: Class selectors should not include a qualifying element.
```

**Would you be interested in submitting a PR for this issue?**

Yup. No problem, though this is likely another issues with the `postcss-less` plugin.

**Comment by jwilsson** [comment]
Thanks for the issue!

It looks like a issue in `postcss-less`, yes. I'll try to create a reduced test case and post there if you don't beat me to it, @JakeSidSmith.

**Comment by jwilsson** [comment]
Actually, when investigating closer I think this is an issue with [postcss-selector-parser](https://github.com/postcss/postcss-selector-parser) and not `postcss-less`.

**Comment by JakeSidSmith** [comment]
Ah, kay. Thanks for doing some research. If I have some time I'll take a look into this, but I'm pretty swamped at the mo.

**Comment by jwilsson** [comment]
Created an issue for it over at postcss-selector-parser: https://github.com/postcss/postcss-selector-parser/issues/109

**Comment by jwilsson** [comment]
Hi!
I know it's a bit late, but we finally got a new release of `postcss-selector-parser` where this issue is fixed. I've just tagged a `lesshint@4.2.0` including that.

**Comment by JakeSidSmith** [comment]
@jwilsson Awesome news. Looking forward to trying it out. :)
