### ISSUE TITLE
Warnings cause exit code 1 by default

### ISSUE THREAD

**Issue by raciat** [lesshint/lesshint#394]
> Passing -1 to the --max-warnings flag is no longer supported. Simply omit the flag for the same behavior.

Ref: https://github.com/lesshint/lesshint/releases/tag/v3.0.0 

**Which version of `lesshint` are you using?** 
3.3.1.

Executing: `lesshint ./src` (without `-x` flag), exits with code 1 and breaks my build.

**What did you expect to happen?** 
Exit with code 0.

**What's the actual result?** 
Exit with code 1.

I did try with `-x false` etc., but it's always the same effect. It only works when I use a number, but I don't want to do that. For sure it doesn't work as states in the docs.

**Comment by jwilsson** [comment]
Hmm, something isn't correct, yes. I'm not sure if it's a docs issue, a bug, or something else just yet (I've been thinking of changing the exit code behaviour when there's only warnings too).

Let me think about it for a little while.

**Comment by tamer1an** [comment]
Thanks @jwilsson  for looking at it  :mag:  we have the same issue.

**Comment by jwilsson** [comment]
What are your feelings about this, @lesshint/team?

Change the current
* Linting errors with a severity of `warning` gives exit code `1`
* Linting errors with a severity of `error` gives exit code `2`

to

* Linting errors with a severity of `warning` gives exit code `0`
* Linting errors with a severity of `error` gives exit code `1`

So builds will only fail when there are actual errors (FWIW, I'm in favor of changing it).

**Comment by kokarn** [comment]
👍

**Comment by JoshuaKGoldberg** [comment]
:+1:

**Comment by jwilsson** [comment]
Thanks for the quick feedback guys!

@raciat and @tamer1an would one of you be interested in submitting a PR changing the exit code behaviour to the one outlined above?

**Comment by raciat** [comment]
@jwilsson sure, I can do that.

**Comment by tamer1an** [comment]
@raciat thanks.
