### ISSUE TITLE
Add support for properties ordered by smacss

### ISSUE THREAD

**Issue by dsandstrom** [lesshint/lesshint#400]
I have grown to like the "smacss" order that is based on [Scalable and Modular Architecture for CSS](https://smacss.com/book/formatting).  Basically, properties are ordered by:
1. Box
2. Border
3. Background
4. Text
5. Other

I have been using it with scss-lint, but would also like it available when working with less.

Here is what scss-lint is using to figure out positioning: https://github.com/brigade/scss-lint/blob/master/data/property-sort-orders/smacss.txt

**Comment by jwilsson** [comment]
Hi!
I'm a bit unsure if this is a good fit for core, for two reasons.

1. It's a bit too opinionated and not "general-purpose" enough.
2. I really don't want to maintain a list of CSS properties 😬  That'll change way too quick.

It sounds like a good idea for a custom linter, though. Take a look at [the docs](https://github.com/lesshint/lesshint/blob/master/docs/developer-guide/linters.md) and [lesshint-browser-support](https://github.com/JoshuaKGoldberg/lesshint-browser-support) for a good example.
