### ISSUE TITLE
Grammar: Each selector should be on it's own line.

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#42]
Hate to be this guy but... Should be: Each selector should be on its own line. Possessive form of "its".

**Comment by jwilsson** [comment]
Well, someone has to be that guy :wink: 

Anyhow, nice catch. Wanna submit a PR for it?
If so, could you point it to the `0.8.1` branch? Thanks!

**Comment by shellscape** [comment]
We're still evaluating lesshint to replace recess in our build tools. Won't be doing any forking until we've decided to roll with the project. Kind of odd to be requesting a PR for a single character change...

**Comment by jwilsson** [comment]
Ah, I see.

No worries, I'll fix it. Any contribution, no matter how small, is awesome :smile:

**Comment by shellscape** [comment]
:+1:
