### ISSUE TITLE
When lesshint encounters erroneous data, it reports no errors

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#43]
I ran lesshint against this silly tidbit:

```
.myclass {
  border: none;
  cursor pointer
}
```

And it produced no output, no errors using default settings. It should have at the least reported on the `border: none;` line, and should have reported an error in the syntax at `cursor pointer`. When I change that line to `cursor: pointer` all is well and I get the error about using 0.

It would appear parsing errors, or syntax errors, are being swallowed.

**Comment by jwilsson** [comment]
Hi,
Thanks for this.

We're currently just silently ignoring the whole file on parse errors (due to the current usage of our Less parser, `gonzales-pe`). I would like to do print the parse error and perhaps rescue the parser but I haven't found a nice way to do this yet. Last time I looked at it `gonzales-pe` just gave us a generic error message but that might have changed since then.

If it's something you want to take a look at, please do! Otherwise I'll see what we can do.

**Comment by kokarn** [comment]
I think we should at least throw and error, so the user knows something's fucky

**Comment by shellscape** [comment]
So here's what gonzales-pe (what a weird name for a module) spits out when there's a parse error:

```
Error: Please check the validity of the CSS block starting from the line #2
    at throwError (/Users/powella/Code/web/web-checkout/node_modules/gonzales-pe/lib/gonzales.css-to-ast.js:15:15)
    at Object.syntaxes.css.getBlock (/Users/powella/Code/web/web-checkout/node_modules/gonzales-pe/lib/gonzales.css-to-ast.js:577:18)
    at Object.syntaxes.css.getRuleset (/Users/powella/Code/web/web-checkout/node_modules/gonzales-pe/lib/gonzales.css-to-ast.js:1304:52)
    at Object.syntaxes.css.getStylesheet (/Users/powella/Code/web/web-checkout/node_modules/gonzales-pe/lib/gonzales.css-to-ast.js:1438:58)
    at Object.rules.stylesheet (/Users/powella/Code/web/web-checkout/node_modules/gonzales-pe/lib/gonzales.css-to-ast.js:322:69)
    at Object.cssToAST (/Users/powella/Code/web/web-checkout/node_modules/gonzales-pe/lib/gonzales.css-to-ast.js:3829:27)
    at repl:1:22
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
```

Not exactly ideal. `lessc --lint` will check a particular file for parse errors before hand, as will the standard `less.render` call when using it programmatically. What would the feeling be on running input files through lessc for parser errors before handing off to gonzales-pe for the AST processing?

**Comment by jwilsson** [comment]
Hmm, that's what I thought. Not much to work with there.

I do feel that running everything through the official Less parser is a bit much. Perhaps we can find some other way.

@kokarn thoughts?

**Comment by kokarn** [comment]
Well, by the looks of it, the first line is actually an error we could present to the user. 
As long as the line number is consistent with the file that should work. 

If not, I think that it's better to just notify the user that the parser failed than to add lessc as a dependancy, at least for now. 

Then we can re-visit it in the future either when gonzales-pe handles it or when demand for that kind of error-reporting is high enough.

**Comment by tonyganch** [comment]
Hello, guys!
Maybe you can describe how you want gonzales to handle errors so we can make a fix?
Right now `ParsingError` is thrown, which has `line` and `syntax` information:
https://github.com/tonyganch/gonzales-pe/blob/dev/src/parsing-error.js
It also has `context` property which returns a formatted string with a broken line like this:
```
246 | @mixin placeholderColor($element, $color)
247*|   #{$element}::-webkit-input-placeholder
248 |       color: $color
```
I can pass more information if you need it, just let me know.

**Comment by shellscape** [comment]
That looks great to me. I'd still like to see some extended message on the sub-type of parse error was offending, if possible.

**Comment by jwilsson** [comment]
I'm with @shellscape to 100%, it looks good but some sort of extended message would be great.

**Comment by kokarn** [comment]
Fixed here https://github.com/lesshint/lesshint/commit/0f7b4dc9dc1e721a9c6cc088ee16784761f5a795
