### ISSUE TITLE
Wrong warning: "singleLinePerSelector: Each selector should be on its own line." 

### ISSUE THREAD

**Issue by rejas** [lesshint/lesshint#466]
**Which version of `lesshint` are you using?**

5.0.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**

CLI and gulp-lesshint

**What's your `.lesshintrc` configuration?**

```js
none
```

**If you're reporting a bug, please show us some code that's failing.**

```less
.a + .a,
.b {
    color: red;
}
```

**What did you expect to happen?**

no warning or errors

**What's the actual result?**

Warning: test.less: line 1, col 1, singleLinePerSelector: Each selector should be on its own line.

**Comment by jwilsson** [comment]
This is fixed in `5.0.1`.

**Comment by rejas** [comment]
Thx @jwilsson Would you also be so kind to propagate it to gulp-lesshint?

**Comment by jwilsson** [comment]
@rejas It should be picked up automatically by updating/reinstalling `gulp-lesshint`.

**Comment by rejas** [comment]
True :-) Have a nice weekend!
