### ISSUE TITLE
Is it possible to lint files with extension that is not 

### ISSUE THREAD

**Issue by handeeadiguzel** [lesshint/lesshint#474]
**Which version of `lesshint` are you using?**
5.1.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
Gulp

**What's your `.lesshintrc` configuration?**
```
{
    "fileExtensions": [".variables", ".overrides"],
    "spaceAfterPropertyColon": {
        "enabled": true,
        "style": "one_space" // Comments are allowed
    },
    "emptyRule": true, // If there are no options for a rule, you can simply enable it by setting it to true
    "importantRule": false // To disable a rule completely, set it to false
}
```

**What did you expect to happen?**
Is it possible to specify a custom fileExtension with a known syntax in the configuration? 
We're using Semantic UI (which is using less) and less files have *.overrides or *.variables extension. 
Would it be possible to configure lesshint to lint files with different extensions ?

**Comment by jwilsson** [comment]
Hi!
Yes, your current configuration should work exactly as you expect. Checking files with the `*.overrides` or `*.variables` extensions. If you want to check `*.less` too, add that as well.
