### ISSUE TITLE
spaceAroundBang not working after variable

### ISSUE THREAD

**Issue by wareczek** [lesshint/lesshint#478]
**Which version of `lesshint` are you using?**
v5.1.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
CLI

**What's your `.lesshintrc` configuration?**
```js
{ "spaceAroundBang": {"style": "before"} }
```

**If you're reporting a bug, please show us some code that's failing.**

```less
.test {
  border-color: #1a69a4!important;
  color: @snowy!important;
}
```

**What did you expect to happen?**
```
Warning: test.less: line 2, col 24, spaceAroundBang: Exclamation marks should be preceded by one space.
Warning: test.less: line 3, col 16, spaceAroundBang: Exclamation marks should be preceded by one space.
```

**What's the actual result?**
```
Warning: test.less: line 2, col 24, spaceAroundBang: Exclamation marks should be preceded by one space.
```

**Comment by jwilsson** [comment]
Hmm, this seems to be an upstream issue. The `important` prop isn't on the AST node. I'll file an issue!

**Comment by jwilsson** [comment]
This should be fixed with a new version of our Less parser in `6.0.0`.
