### ISSUE TITLE
False Positive with "spaceBeforeComma"

### ISSUE THREAD

**Issue by CITguy** [lesshint/lesshint#49]
`spaceBeforeComma` returns a false positive with the following LESS file

```less
@var: (4 / 2);
```

`test.less: line 1, col 9, spaceBeforeComma: Commas should not be preceded by any space.`

Yet, returns no errors with the following LESS file

```less
@var: (4/ 2);
```

Please update to allow space before LESS operators.

**Comment by CITguy** [comment]
FYI: This is using `lesshint 0.8.0`.

**Comment by jwilsson** [comment]
Since I'm stuck on a train I had the time to fix this straight away. Hope this solves it!

**Comment by CITguy** [comment]
Looks like it should work. How can I test this?

**Comment by jwilsson** [comment]
I think you can specify a Git URL in your `package.json`, for example:

```
"devDependencies": {
  "lesshint": "https://github.com/lesshint/lesshint.git",
  ...
}
```

**Comment by CITguy** [comment]
Something's not working quite right. I run `node_modules/lesshint/bin/lesshint src/` and nothing happens, but when I run the globally installed lesshint via `lesshint src/` I get report output.

**Comment by CITguy** [comment]
*note:* globally installed lesshint is not the github version but the one retrieved from npm

**Comment by kokarn** [comment]
You can use npm install -g with the link to the repo directly to install
the latest version.

http://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly

**Comment by CITguy** [comment]
Ah, it seems to work that way. Thanks @kokarn

**Comment by kokarn** [comment]
No worries, happy to help :)
