### ISSUE TITLE
I got the "parse error: Unknow word / parse error: Unclosed block", is it a lesshint bug itself?

### ISSUE THREAD

**Issue by zhangzhiqiang37** [lesshint/lesshint#490]
**Which version of `lesshint` are you using?**
5.1.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
CLI

**What's your `.lesshintrc` configuration?**

```js
module.exports = {
  fileExtensions: ['.less', '.css'],

  spaceAfterPropertyColon: false,

  spaceBeforeBrace: false,

  newlineAfterBlock: false,

  zeroUnit: false,

  singleLinePerProperty: false,

  propertyOrdering: false,

  stringQuotes: false,

  maxCharPerLine: false,

  hexLength: false,

  hexNotation: false,

  decimalZero: false,

  duplicateProperty: false,

  spaceAroundComma: false,

  trailingSemicolon: false,

  emptyRule: false,

  importantRule: false,

  trailingWhitespace: false,

  spaceAroundOperator: false,

  finalNewline: false,

  spaceAfterPropertyValue: false,

  universalSelector: false,

  singleLinePerSelector: false,

  propertyUnits: false,

  spaceAroundBang: false,

  importPath: false,

  spaceAfterPropertyName: false,

  urlFormat: false,

  attributeQuotes: false,

  comment: false,

  depthLevel: false,

  decimalZero: false,

  selectorNaming: false,

  idSelector: false,

  hexValidation: false,

  borderZero: false,

  colorVariables: false,

  spaceBetweenParens: false,

  variableValue: false,

  urlQuotes: false,

  qualifyingElement: false,

  importantRule: false
};
```
Yes! we just check sytax error!

**If you're reporting a bug, please show us some code that's failing.**

```less
.w(@w){width:@w}
```

**What did you expect to happen?**
I think these codes runs exactly right just like:
```less
.w(@w){
  width:@w
}
```
But they are different in lesshint!
**What's the actual result?**
```
Error: fn.less: line 19, col 1, parse error: Unclosed block
```

**Another case**
The similarity case:
```less
.icon_emoji_ios_0{._bgSprite("icon/common/emotion_panel/emoji_ios/u1F604.png")}
```
```
Error: emoji_ios.less: line 3, col 78, parse error: Unknown word
```

**Would you be interested in submitting a PR for this issue?**
Unfortunately that would beyond my abilities.

**Comment by jwilsson** [comment]
Hi!
Thanks for the report!

The first error seems to be related to [this one](https://github.com/shellscape/postcss-less/issues/88) in our Less parser (the missing semicolon is the culprit).

The second error is also an issue in our Less parser, I've filed [an issue](https://github.com/shellscape/postcss-less/issues/110) over there.

Adding semicolons before `}` will solve both issues, just as a workaround for now.

**Comment by jwilsson** [comment]
This should be fixed with a new version of our Less parser in `6.0.0`.
