### ISSUE TITLE
Error by using less maps

### ISSUE THREAD

**Issue by mhauens** [lesshint/lesshint#492]
**Which version of `lesshint` are you using?**
5.1.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
"lesshint-webpack-plugin": "^0.0.4",

**What's your `.lesshintrc` configuration?**

```js
{
    "emptyRule": false,
    "spaceAfterPropertyName": false,
    "propertyOrdering": false,
    "zeroUnit": ["no_unit"],
    "importPath": [true, false],
    "singleLinePerSelector": false,
    "qualifyingElement": false,
    "universalSelector": false,
    "duplicateProperty": ["display"],
    "maxCharPerLine": 150,
    "importantRule": false
}
```

**If you're reporting a bug, please show us some code that's failing.**

```less
@sizes: {
  mobile: 320px;
  tablet: 768px;
  desktop: 1024px;
}
```
http://lesscss.org/features/#maps-feature

**What's the actual result?**
parse error: Expected a pseudo-class or pseudo-element.

**Comment by jwilsson** [comment]
Hi!
This seems to be an issue with our [Less parser](https://github.com/shellscape/postcss-less/). I'll file an issue over there.

**Comment by jwilsson** [comment]
This should be fixed with a new version of our Less parser in `6.0.0`.
