### ISSUE TITLE
Add ability to disable linting for a single line

### ISSUE THREAD

**Issue by CITguy** [lesshint/lesshint#55]
Other linters/hinters have the ability to ignore linting on a single line via a trailing comment. It would be very useful to have this ability. An example...

My team discourages the use of `!important` but there are edge cases where it needs to be used.  As such, it would be useful to enable `importantRule` globally, but apply something like `// lesshint ignore:line` that would ignore linting for a specific line, so that I can allow `!important` in edge cases (bonus points if we can just ignore the single rule via `// lesshint ignore:importantRule`).

**Comment by CITguy** [comment]
It should be trivial to implement `// lesshint ignore:line` as it would be a matter of removing lines from the incoming css *before* parsing with gonzales (similar to how we already [normalize line endings](https://github.com/lesshint/lesshint/blob/master/lib/linter.js#L76)).  This way, the entire line is completely excluded from the resulting AST.

Rule-specific disabling may be trickier as we would have to walk the sibling nodes until we encounter a *singlelineComment + newline*, then parse the comment to check if the rule is ignored.

**Comment by kokarn** [comment]
I think we should go for // lesshint ignore:importantRule. It's a really
nice feature and I see no reason to go half-assed.

**Comment by jwilsson** [comment]
I agree with @kokarn, we should definitely take the time to work this out properly since I think it's a real "must-have" feature.

**Comment by shellscape** [comment]
Carried over from #57, declaring per-file options in a comment at the top of a file goes along with this. Since the other was closed, perhaps renaming this for both type of inline/infile options is appropriate.

**Comment by shellscape** [comment]
@kokarn jshint syntax, which I think works really well in this case, follows their .jshintrc syntax. eg:

```
.somerule { background: url(...); } /* lesshint urlQuotes: false */
```

or

```
/* lesshint urlQuotes: false */
.somerule { background: url(...); } 
```
that makes configuring lesshint uniform wherever you choose to; .lesshintrc, inline, etc.

**Comment by kokarn** [comment]
Yeah, that seems like a good way to do this. :+1:

**Comment by shellscape** [comment]
Starting work on this one. Tracking on https://github.com/gilt/lesshint/tree/inline-rules

**Comment by cageygee3** [comment]
Would love to see this in action as well. For our project, we always alphabetize our properties, but there are a couple cases where it makes sense to not do this:

- `display: none` comes first (usually with a comment explaining why)
- Browser-specific properties usually mess up the ordering of things

Any status update?

**Comment by jwilsson** [comment]
Totally forgot about this one. I don't think anyone's working on it but I'll be happy to do so unless someone else is interested (@shellscape?).

What I'm proposing is basically what we discussed earlier so we're consistent with `.lesshintrc`.

Disable rule for a single line (add any type of trailing comment):
```
.somerule { background: url(...); } /* lesshint urlQuotes: false */ or // lesshint urlQuotes: false
```

Disable rule for the whole file (add a any type of comment at the top):
```
/* lesshint urlQuotes: false */ or // lesshint urlQuotes: false
.somerule { background: url(...); } 
```

**Comment by cageygee3** [comment]
Sounds good to me. :+1:

**Comment by shellscape** [comment]
I had started poking at this but got distracted by the PostCSS LESS syntax thing. And then our company got purchased so it's been a little crazy on my end. Should even out after this month - but please do take a look at that branch and continue on in the mean time!

**Comment by adam-lynch** [comment]
Definitely need this :+1:

**Comment by jwilsson** [comment]
Some feedback over in #138 would be greatly appreciated :smile:
