### ISSUE TITLE
Linter refactoring

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#56]
Continuing on our discussion in #47.

We have some ways in which we would like to change the linters to avoid code duplication.

### Disabling linters
Right now each linter checks whether or not it's disabled. In order to avoid lots of code duplication I'm proposing a move of this code to the main AST traversing, before the linter is even called. This might even result in the ability to just load the linters that are enabled in the user's `.lesshintrc`.

### Rule severity
We talked about how to override this in #47 while avoiding as much code duplication as possible. Unfortunately I haven't come up with any good ideas on how to specify the severity of a violation other than to include it in each linter. Perhaps someone else has? If so, tell us! Otherwise, I guess we'll have to include some sort of code in each linter.

**Comment by kokarn** [comment]
I quite like the eslint way, to specify it in the first argument for the linter. 
1 is warning, 2 is error.

```json
{
     "space-in-parens": [
          1,
          "always",
          {
               "exceptions": [
                    "{}",
                    "()"
               ]
          }
     ],
     "space-before-function-paren": [
          2,
          "never"
     ],
     "space-unary-ops": 2,
     "no-spaced-func": 2,
     "no-multiple-empty-lines": 2,
     "no-multi-spaces": 2
}

**Comment by shellscape** [comment]
I'm planning on adding time for this to our next sprint, FYI.

**Comment by jwilsson** [comment]
:+1:

**Comment by jwilsson** [comment]
@shellscape :+1:

**Comment by shellscape** [comment]
Created #63 to continue discussion.
