### ISSUE TITLE
Inline Options

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#57]
With tools like jshint, we're able to define configuration options for a file as an inline comment at the top of the file (and throughout code for blocks). I haven't been able to find any mention of an option like this for recess as yet, but something like that on the file-level would be immensely helpful.

When we were still using recess, we implemented a similar feature in a fork of gulp-recess: https://github.com/shellscape/gulp-recess-plus/commit/be65783160760c9d8bbc44d71724aa79098dc680

**Comment by jwilsson** [comment]
We started talking about something like this in #55. Let's continue the discussion there.
