### ISSUE TITLE
Sorting Results by Line Number

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#58]
I traced this back to lesshint, as the reporters and gulp-lesshint are just passing the data along. Line numbers aren't always in order, and that would be super keen for reporting. See this sample output from one of our real-world files:

```
/Users/.../src/reset.less
  line 76  col 12  Strings should use single quotes.
  line 23  col 3   Property ordering is not alphabetized
  line 45  col 3   Duplicate property: "content".
  line 45  col 3   Property ordering is not alphabetized
  line 80  col 3   Property ordering is not alphabetized
```

**Comment by jwilsson** [comment]
Yeah, that makes sense. Since the linters are ordered alphabetically, the errors are sorted the same way. But I agree that we should order them by line number.
