### ISSUE TITLE
Alphabetized Property Names + Vendor Prefixes

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#59]
I'm getting a peculiar false positive with vendor prefixes and the alphabetization linter. The code below is throwing a warning for not being alphabetized. Am I missing something, or is the linter misbehaving?

```less
  background-image: -moz-linear-gradient(top, #FEFEFE, #EAEAEA);
  background-image: -ms-linear-gradient(top, #FEFEFE, #EAEAEA);
  background-image: -o-linear-gradient(top, #FEFEFE, #EAEAEA);
  background-image: -webkit-gradient(linear, left top, left bottom, from(#FEFEFE), to(#EAEAEA));
  background-image: -webkit-linear-gradient(top, #FEFEFE, #EAEAEA);
  background-image: linear-gradient(top, #FEFEFE, #EAEAEA);
```

**Comment by jwilsson** [comment]
I don't we ever specified how to handle hyphens, but I also think we should sort them before letters.

**Comment by shellscape** [comment]
The sorting that's already implemented seems to handle hyphen or non-alpha-first fine for the most part. But it's on this particular block that the sorting gets wonky. It passed successfully in other files we ran against.

**Comment by jwilsson** [comment]
Hmm, strange. I'll look into it if no one else beats me to it.

**Comment by jwilsson** [comment]
Alright, I think I've found the issue. 

`localeCompare` returns `0` when the checked values are identical and we mark it as a violation if  `localeCompare` returns `> -1`.

**Comment by shellscape** [comment]
:+1:
