### ISSUE TITLE
Remove quote style option from attributeQuotes

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#65]
Looking at #23, we currently have a quote style option on `attributeQuotes`. I think we could remove this and let `stringQuotes` handle this instead and just check for the existence of quotes in `attributeQuotes`.

**Comment by kokarn** [comment]
What would the difference be? Anything at all?

**Comment by jwilsson** [comment]
No, not really. Just less code in `attributeQuotes`.

**Comment by kokarn** [comment]
:+1: Go! ^^

**Comment by CITguy** [comment]
:+1: let `stringQuotes` handle it
