### ISSUE TITLE
Merge spaceAfterComma and spaceBeforeComma

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#66]
It seems kind of unnecessary to have to separate linters which basically checks the same thing. 

I'm proposing a merge of these two into a `spaceAroundComma` linter with the following options:
* `none`
* `before`
* `after`
* `both`

**Comment by kokarn** [comment]
Only thing this would remove is the possibility to set one as warning and the other as error. 
Doesn't feel like that is reason enough to keep them separated.

**Comment by CITguy** [comment]
I agree with @jwilsson. At least with the teams I work with, we only care about one or the other, so combining them would reduce configuration options and make it easier to consume.

**Comment by jwilsson** [comment]
I forgot to mention this in the original description, but I propose `after` as the default value.

Some quick examples for reference:

```css
rgb(0,0,0) // none

rgb(0, 0, 0) // after

rgb(0 ,0 ,0) // before

rgb(0 , 0 , 0) // both
```

**Comment by kokarn** [comment]
:+1:

**Comment by CITguy** [comment]
+1 `after`

**Comment by CITguy** [comment]
Can this be updated to be `spaceAroundOperators` so it will apply to `+`, `-`, `*`, `/`, etc. as well?

**Comment by kokarn** [comment]
That's a great idea, with an option for each operator

**Comment by jwilsson** [comment]
Perhaps we should create a new linter named `spaceAroundOperator` which checks `+`, `-`, `*`, `/`, and `=` and leave commas to this one?

**Comment by kokarn** [comment]
Why separate commas into their own linter? Because it's not an operator?

**Comment by jwilsson** [comment]
Yeah, I'm thinking just in case someone wants to do it separately it can be quite a lot of options and it would be nicer to separate them. But if more people are in favor of combining than against it we'll go with that.

**Comment by kokarn** [comment]
I vote for one linter, @jwilsson for two.

@CITguy @shellscape

**Comment by shellscape** [comment]
agree with @jwilsson. always in favor of separation of concerns, even if there is a little bit of duplication.

**Comment by kokarn** [comment]
I'd say it's settled on two linters then, even if @CITguy for some reason disagrees.

**Comment by shellscape** [comment]
@jwilsson @kokarn has anyone started on this? I'll tackle it next week if not.

**Comment by kokarn** [comment]
@shellscape No not yet so feel free :)

**Comment by shellscape** [comment]
Created the branch. I'll start work tomrrow

**Comment by kokarn** [comment]
:+1:
