### ISSUE TITLE
Specs fail on gonzales-pe@3.0.0-beta

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#78]
We're going to want to update lesshint for gonzales-pe 3.0.0-beta, as many things have changed and about half of our specs fail when using it.

We should probably hold off on releasing 1.0.0 until gonzales-pe is out of beta, since there are a lot of bugs with it just yet.

**Comment by kokarn** [comment]
Have you heard of any timeframe for 3.*? Is it worth waiting for or is it just easier to update once it's released?

**Comment by shellscape** [comment]
I looked around their repo and I didn't see a milestone list or timeframe. I think he's got a ton of bugs to contend with. I just submitted one to him today where the less helper function spec wasn't being honored. 3.0.0-beta affords us better error reporting, among other improvements, and that's a big draw. I'd say we should at the least branch and get everything working with 3.0.0-beta now; it'd be prudent. Anything that's a bug we can submit and flag in code for further review.

**Comment by kokarn** [comment]
Sure, as long as it's not actual regressions. I agree that we should at least test it out but i'm a bit reluctant to go towards a beta version of something that might be beta for a long while. 

But as long as the tests succeed I can't really say we shouldn't :)

**Comment by shellscape** [comment]
It looks like he's close to a stable 3.0.0 release. Has a few bugs to contend with, but seems to be a priority https://github.com/tonyganch/gonzales-pe/issues/94

**Comment by kokarn** [comment]
That looks great. Let's wait for that and sync our 1.* with gonzales-pe's 3.*

**Comment by jwilsson** [comment]
Most work is done in #81.
