### ISSUE TITLE
Get lesshint on lesscss.org

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#79]
The project should definitely find a niche on this page somewhere http://lesscss.org/usage/. It's not 1.0.0 just yet but deserves the visibility bc awesomeness.

**Comment by kokarn** [comment]
:+1: Agreed.

Somebody should write a PR for https://github.com/less/less-docs
@jwilsson ?

**Comment by jwilsson** [comment]
Oh, definitely. I'll do it once we hit 1.0.

**Comment by jwilsson** [comment]
I forgot to update you guys on this.

It's been added to the Less docs repo and should be published on the site soon :tada:

**Comment by shellscape** [comment]
AWESOME
