### ISSUE TITLE
importPath doesn't handle URIs without quotes

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#80]
First reported by @alferov over at lesshint/gulp-lesshint#1.

It looks like we're a bit to naïve when checking URIs in `importPath`. We always assume a string which of course isn't always the case.

This is a great candidate for a first issue, on line 24 of https://github.com/lesshint/lesshint/blob/master/lib/linters/import_path.js we need to check for both strings and "raw" URIs and make sure whichever one we find is the value being checked.

**Comment by kokarn** [comment]
Reopened so it's clear that we still need to check for `@imports` without quotes

**Comment by rmbl** [comment]
Should be fixed with #86 I hope.
