### ISSUE TITLE
gonzales-pe increasingly unstable

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#89]
Just raising this issue for awareness. gonzales-pe has become increasingly more unstable since approaching and passing 3.x. Nearly all of our less files have false positive syntax failures on 3.2.1, simply because gonzales-pe isn't validating things correctly. We're still waiting for the project to fix several mixin-related false positives, including basic mixin definition syntax.

To make matters worse, the project is built/compiled in a way that makes it extremely difficult to debug. 

Are there alternatives to gonzales-pe that are worth exploring?

**Comment by kokarn** [comment]
I think @jwilsson did a check when he started lesshint and couldn't really find anything IIRC. 
That's almost a year ago so it might be worth looking again.

**Comment by jwilsson** [comment]
Yeah, I looked around when I first started and didn't find any other parsers. The official Less parser doesn't officially expose the parse tree but I managed to hack something together that would let me inspect it but no spaces etc. are included, just the already parsed value.

That's one of the main reasons why I chose to go with `gonzales-pe` since all spaces etc. are exposed. And the API that `gonzales-pe` exposes is quite nice to have.

I don't know how we should proceed really, if we should try to help out and fix the issues in `gonzales-pe` either by submitting them upstream or fork it and use that instead (while still submitting them upstream but using our fork in `lesshint`), build our own parser (extreme, I know) or continue looking for another parser. I don't think we can use the official Less parser since that would make a lot of the current rules near impossible, if not impossible, to implement.

**Comment by shellscape** [comment]
Yeah I just took a look at the less.parse and ParseTree implementations that the current version is using, and while it's damn fast, it doesn't include any meta data like spacing. I'll take a look around and see if something new has popped up. But gonzales-pe has real issues after 3.x - we've got rules that haven't been touched in over a year that are now throwing syntax errors. No bueno.

**Comment by shellscape** [comment]
Fwiw, I've been trying to work on an issue with variable dictionaries in gonzales for the past month, and the structure and test process of the project is incredibly convoluted. I'm no slouch, and I haven't been able to fix a simple issue yet.

**Comment by jwilsson** [comment]
@shellscape I've been trying to fix some of the issues as well and have also been struggling, so you're not alone :)

I'll think for a little bit and see if I can come up with another solution on how we should proceed with this.

**Comment by shellscape** [comment]
In the meantime I'm trying to come up with a solution to easily debug that crazy thing. I've zero clue why he's minifying and restructuring the code when it's not used on the client-side.

**Comment by shellscape** [comment]
@jwilsson going to look into postcss today, as that reportedly can produce an ast faster than less.js.

**Comment by jwilsson** [comment]
@shellscape Awesome! Thanks for checking.

I just want to start out by saying that I'm definitely not against using `postcss` (or anything else for that matter, the important thing is that we're able to parse the code and get a nice tree to work with).

Some things I thought of during a quick look at `postcss`:

* How much Less syntax is currently supported by `postcss` plugins? I can't seem to find any mixin or extend plugins. We'll obviously write our own if needed, just wanted to check on the amount of work or if anyone knows of a mixin and/or extend plugin. I did, however, managed to find a Less variable plugin: https://www.npmjs.com/package/postcss-less-vars. And nested rules seems to be possible too: https://www.npmjs.com/package/postcss-nested. I've probably missed some Less feature(s) but this is a start.

* There seems to be enough space information but other linters, for example `attributeQuotes`, the `hex*` ones, and the `url*` ones will need some work (maybe not that big of an issue?). The extra work that's needed here consists of extra parsing of attribute selectors, right now we're passed a parsed selector by `gonzales-pe` which contains a bunch of different nodes so we just check for the existence of a string in one of them. Colors and URLs are currently exposed as `color` and `uri` nodes respectively so they're super easy to check. These will need extra parsing by us after being emitted by `postcss`, see a simple gist here: https://gist.github.com/jwilsson/5eeca1fa0422e1d59a3c

I'm still a bit unsure on what I think and feel. Whether we should continue with a third party parser or try to build our own. I know it's *a lot* of work but that way we can build something really nice and have full control over everything (bug fixes, performance issues, code readability etc.). But as far as I'm concerned all doors are still open.

**Comment by shellscape** [comment]
Yeah, no worries. This is strictly an informational exercise right now. I'm not suggesting the project switch either, just taking a look at what else might be out there now.

You hit the nail on the head with those points. We'd definitely be looking at additional work for parsing the extras that gonzales provides out of the gate. In all likelihood, that extra work would probably be best suited for a separate project housing the extras+postcss, which lesshint would then consume. 

There are also going to be gotcha's that come up, such as https://github.com/postcss/postcss/issues/617

Of the alternatives that I've taken a look at so far, this one seems the most viable.

**Comment by shellscape** [comment]
Got a great answer from the postcss guys. They pointed me at https://github.com/postcss/postcss/blob/master/docs/syntax.md and https://github.com/postcss/postcss-scss which looks like a good place to start.

**Comment by jwilsson** [comment]
Looks promising, could definitely be one way to do it.

**Comment by shellscape** [comment]
Starting to poke at this tonight, and see if I can't get some less parsing. At the very least, should gain some greater understanding of the css/less AST.

**Comment by shellscape** [comment]
I got a new syntax for postcss going; https://github.com/gilt/postcss-less

It's surprisingly easy to work with. Things are first tokenized, and then those tokens are read and analyzed and turned into nodes for the tree. So far I have variable interpolation and mixins parsing. (things like inheritance, nesting, parent selectors are there by default). While it includes spaces and such in the tree that's returned, it lacks nodes for combinators and brackets, parens, etc. From what I can tell, those would be relatively easy to add. Overall it's an extremely straight-forward project. Check out the tests and the scss-tokenizer.es6 file (still need to rename those).

**Comment by jwilsson** [comment]
@shellscape Awesome!

I agree, the code looks really straightforward, I'll try to help out as much as I can.

**Comment by shellscape** [comment]
Got mixins into their own node type, and got parameter parsing working correctly as far as I can tell. Some TODOs at the bottom of /test/parser.es6. (should probably create issues to track that, but it's early yet).

What I could really use help with is adding more tests for LESS specific syntax that fail, so the support can be written for them. PostCSS is really good about complaining about stuff it doesn't recognize, but there's little built in for syntax errors outside of base CSS syntax. It catches stuff like unmatched pairings (parens, curlies, etc). But stuff like commas instead of semicolons for parameter delineation in mixins are passing through without error.

**Comment by shellscape** [comment]
@kokarn @jwilsson @CITguy can you guys please ping the gonzales-pe team about the pending pull requests? I've got a feeling he's miffed, still hasn't merged any fixes, and the latest 3.x is breaking on legit less syntax.

**Comment by shellscape** [comment]
@kokarn we've decided to use our fork of gonzales-pe while we're waiting. I just fixed variable strip-quote directives `@var: ~"value";` - https://github.com/gilt/gonzales-pe/commit/a655833ba60ec62072853ea32610260d2c2b4453

And using our fork of lesshint only because we have to override the instance of gonzales that lesshint uses while we're waiting: https://github.com/gilt/lesshint/commit/3d4c0af427e3dfe3569f6f5c9c8d6fac79f3cb8d - @jwilsson I wasn't sure if that was a value-add for lesshint, so I held off on a PR.

With all those merged changes merged into the fork, gonzales-pe is letting our less through to lesshint and our build processes can continue :tada:

**Comment by jwilsson** [comment]
@shellscape I'm totally open to it, if everything's working for you guys (it seems like you got quite a complex code base) and if @kokarn could try it out too with his code base I think we could use that your so we can move forward with new linters and perhaps don't have to spend that much time on a new parser and the related work with rewriting all the linters.

But on second thought, I'm a bit worried that our fork will stray too far off the original one and we'll end up with big problems. Are there any other pros/cons that you can think of?

**Comment by shellscape** [comment]
Yeah getting out of sync is a big concern. We're viewing the fork here as temporary while we wait for the project to get fixes in there, and while we're working on postcss-less. With the community and activity of postcss, I really think it has great potential as the way forward. A few ugly patches on a fork of gonzales-pe is good enough for the time being (for gilt).

**Comment by kokarn** [comment]
We could actually just do a fork and then stop. There shouldn't really be any more updates needed for gonzales for us to use it correctly so we can just make it stable and then just keep it that way. Then we can focus on the postcss stuff as i believe that's the way forward as well.

**Comment by jwilsson** [comment]
After some additional thinking I came up with that idea too, use the fork for now while we finish the PostCSS parser which would be great to use since we're in full control of the parser then.

**Comment by shellscape** [comment]
:+1: just finished "fixing" the last of the bugs for our fork that came up with our less files. We're using it internally here, but in fairness you guys should evaluate it. We haven't seen any ill effects with lesshint yet.

**Comment by kokarn** [comment]
Let's let it mature for a week or two and then see how it works out. I'm all for going that way tho.

**Comment by jwilsson** [comment]
Sounds good, I'm gonna take the fork for a spin with some Less frameworks etc. to see if there are any other issues (figuring there should be some pretty complex Less there).

**Comment by shellscape** [comment]
We just found two more problems today. Another user posted an issue on gonzales-pe that keyframes are broken, and we just ran into that this morning. We're also having trouble with `ul > li > .thing` now. Just a cluster-f of a release.

**Comment by kokarn** [comment]
How much work would you estimate it is to downgrade and what would be
broken if we did?

**Comment by shellscape** [comment]
I've honestly no idea. That'd be a question for @jwilsson.

**Comment by jwilsson** [comment]
Sorry for the silence guys, been a crazy couple of days.

I ran the fork on some frameworks using Less, Bootstrap and Skeleton among others, and the issues I found were:
* [% format function](http://lesscss.org/functions/#string-functions--format), for example this line from Bootstrap's `less/mixins/gradients.less`:
```less
filter: e(%("progid:DXImageTransform.Microsoft.gradient(startColorstr='%d', endColorstr='%d', GradientType=1)",argb(@start-color),argb(@end-color))); // IE9 and down
```

* [Guarded Namespaces](http://lesscss.org/features/#mixins-feature-guarded-namespaces)/[Mixin Guards](http://lesscss.org/features/#mixin-guards-feature), like this line from Bootstrap's `less/mixins/grid-framework.less`:
```less
.calc-grid-column(@index, @class, @type) when (@type = width) and (@index > 0) {
```

* Inline JavaScript code, for example:
```less
 content: `"foo".toUpperCase()`
```

@shellscape's fork handles everything else. I don't think that it's that much work to downgrade but it just feels too extreme. I think we should be fine using the fork and try and work as hard as possible on the PostCSS parser.

**Comment by shellscape** [comment]
No worries here. If I told you about my last few weeks between work and personal you'd probably poop masonry. 

The % format should be an easy fix in the fork. The guard is a whole 'nother ball of wax, and there's still a pending request for that on gonzales' issues. I looked into it briefly but it's a complex problem. I didn't even know that inline javascript was possible :D but that should be nothing more than checking for backticks, which should be easy to setup.

With the fork working well for us, we're going through an internal update from an old Rake-based tooling to a Gulp-based tooling (which includes lesshint!) so that's where most of my time is sucked into right now. We're a week or two away from being done with that, which means I'll get to shift time back to stuff like PostCss' less syntax. 

(dev/master of gonzales-pe hasn't seen any activity in three weeks. looks like there's misc work being done on branches, but nothing towards less or scss)

**Comment by kokarn** [comment]
@jwilsson, would you mind running the same frameworks with the current
gonzales-pe in lesshint?
I assume there will be errors thrown there as well and it would be very
interesting to compare.

**Comment by jwilsson** [comment]
@kokarn I'll take a look tonight.

**Comment by jwilsson** [comment]
Apart from the things above this is what I found (duplicate errors not included):

Bootstrap's `less/alerts.less`
```less
> p + p {
```

Bootstrap's `less/badges.less`
```less
a& {
```

LESS Hat's `build/lesshat-prefixed.less`
```less
.lh-align-content(...) {
```

Sometimes it's reporting parse errors on these types of lines which just seems absurd so I think that's something else.
```less
&:active, // Boostrap's less/mixins/buttons.less:22
```

Basically what I found are the things @shellscape has fixed in the fork already. 

For the record, these are the frameworks tested:
* [Bootstrap 3.3.5](https://github.com/twbs/bootstrap)
* [Cardinal 3.2.6](https://github.com/cbracco/cardinal)
* [LESS Hat 3.0.2](https://github.com/madebysource/lesshat)
* [Skeleton Less port @874cef2](https://github.com/WhatsNewSaes/Skeleton-Less)

I tested by running this (crude) command and looked at the offending lines for each library:
```bash
./bin/lesshint [path to framework] | grep parse
```

So most things are fixed in the fork already, Guarded Namespaces and Mixin Guards feels like the big problem. The other problems I found doesn't seem that tricky or widely used either.

**Comment by kokarn** [comment]
Okey, that makes sense. Would you mind testing with an old version of gonzales as well? Just for comparison. That way we can make a well informed decision on a good way forward.

**Comment by jwilsson** [comment]
Alright @kokarn, I've tested the above frameworks with lesshint@e718226 which means:
* That's the last commit before the `gonzales-pe`update from `3.0.0-31` to `3.0.0-beta` and then a stable `^3.0`.
* I've also applied the bug fixes from 06bee99 and 91cf906 or everything would crash.
* This gave us these parse errors:

Bootstrap's `less/forms.less`:
```less
right: floor((@grid-gutter-width / 2));
```

Cardinal's `base/mixins/to-rem.less`:
```less
@{property-px}+_ : ~"@{px-value}";
```

I didn't find any other errors but on Boostrap a lot of the parse errors were submitted without a line, not sure why that is, but I guess it's serious. It's also still failing on the [% format function](% format function) and inline JavaScript. 

I think we should switch to @shellscape's fork, tag a new version, and continue working on other issues, features, and of course the PostCSS parser. If the majority think we should revert to `gonzales-pe 3.0.0-31` what we need to do is:
* Revert ac47970, f16f7d6, and 9cba245.
* Possibly re-apply fixes for the bugs corrected in `1.0.1`.
* Probably something more related to other issues which will surface.

**Comment by kokarn** [comment]
After all this testing I must say I agree. The fork seems like something we
could use as a great base and then focus on PostCSS

**Comment by jwilsson** [comment]
I'll submit a PR in just a little bit using @shellscape's fork.

**Comment by thybzi** [comment]
For now, lesshint still uses gonzales-pe. It what future version it should move to PostCSS?

**Comment by shellscape** [comment]
@thybzi the postcss-less parser isn't ready yet. I barely scratched the surface, and had to put it on the back burner temporarily. The base parser picks up a *ton* of stuff that's part of the less syntax, but it needs additions. The fork is here: https://github.com/gilt/postcss-less and I would absolutely welcome contribution. I should be picking up work on it again in the near future. Once it's comprehensive, then we can evaluate it for a switch. If we decide to pull the trigger, all of the linters will need to be updated, and that is going to be a task. Given the stagnation and apparent disregard for all of the parser errors on gonzales-pe's Issues, I still think this is a good move for the future.

**Comment by shellscape** [comment]
And I just ran across this project here: https://github.com/webschik/postcss-less

**Comment by kokarn** [comment]
That actually looks quite good. Maybe focus on that one instead?
Any comparison to yours Andrew?

**Comment by shellscape** [comment]
@kokarn haha it's the same initial fork of postcss-scss. if you diff the code, you'll see it's actually not as far a long as the gilt fork.

**Comment by kokarn** [comment]
oh sorry, I just checked the commits and it looked good ^^

Maybe try to talk to them and see if they want to join in work on the gilt
version instead?

**Comment by thybzi** [comment]
Good idea to cooperate if we pursue similar goals
