### ISSUE TITLE
New Linter: Mixin Rule First

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#90]
We've been catching a lot of alphabetizing offenders lately, thanks to the new addition a little while ago :) 

As such, people have complained that it's not immediately obvious that mixin rules should be declared first (same with vendor-specific rules). I can see a new linter for validating that mixins are at the top of the rule stack when someone doesn't want to enforce alphabetizing. It'd also be a good linter for folks using alphabetizing, as the message that would accompany it would be pretty clear.

```
.selector {
  border: 1px solid #000;
  .transition-mixin;
  width: 100px;
}
```

vs

```
.selector {
  .transition-mixin;  
  border: 1px solid #000;
  width: 100px;
}
```

Thoughts?

**Comment by kokarn** [comment]
Yeah, `mixins-on-top` or `mixins-first` is a great linter i think. :+1:

**Comment by jwilsson** [comment]
Absolutely! :+1: from me

**Comment by shellscape** [comment]
So the gilt fork is still on `"0.9.4"` because gonzales-pe hasn't yet addressed some pretty nasty less-breaking bugs (I've got PRs up there for them, but oh well). We can't bump to `master` of lesshint until those are fixed, or our less linting will start throwing false positives and we won't be able to deploy parts of our site; not a good thing :)

I'm going to write the linter on that version, and cross my fingers that it works with master. At the very least, the PR might need tweaking to work with master.

**Comment by kokarn** [comment]
Sounds good. 
Just noticed a few more issues with gonzales today, we shouldn't have updated :(

**Comment by shellscape** [comment]
@kokarn can always revert, but I'm assuming that's last resort.

**Comment by kokarn** [comment]
We've updated quite a lot for 3.* so it's a lot of work for something that really shouldn't be an issue :/ Rather focus that dev time on the postcss thing ;)

**Comment by shellscape** [comment]
@kokarn not to get too far off topic - would you like committing access to the dev repo for postcss-less?

**Comment by kokarn** [comment]
Sorry, won't have time to help out in the foreseeable future i'm afraid. 
Give it to @jwilsson if he doesn't have it already tho :)

**Comment by adam-lynch** [comment]
:+1:

**Comment by shellscape** [comment]
I suspended development of this linter since Gilt doesn't have the need for it anymore. Will reopen and pick back up if needed in the future.
