### ISSUE TITLE
propertyOrdering: alpha doesn't consider mixins

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#94]
As discovered while writing mixinOrdering, mixin calls within rule blocks aren't considered properties, but are labeled as type 'include' by gonzales-pe, and have a different means of getting the content.

```
if (element.type === 'include') {
  property = element.first('class');
  content = property.content.toString();
}
```

**Comment by jwilsson** [comment]
Do we want to enforce alphabetical ordering for mixins? Couldn't there be instances when the order matters?

**Comment by kokarn** [comment]
Yeah, there are a lot of legitimate reasons for now having those in alpha order.

```less
.my-block {
    .wrapper();
    .block();
    .action();
}
```
would probably output a totally different css than
```less
.my-block {
    .action();
    .block();
    .wrapper();
}
```

**Comment by shellscape** [comment]
There are likely edge use-cases where the ordering does in fact matter. I was going to put a PR together for this one and add a ```mixins: false``` (default) option for this. `true` would consider mixins, `false` would not. I'd be good either way for the value of the default value.

As an alternative, this could go into the mixinsOrdering linter as well. Would just need to rethink the options for that one, because `first` and `last` are solid. We'd need a logical option for specifying the method of sorting as well. Thoughts?

**Comment by kokarn** [comment]
I actually don't see this as something that will break "edge use-cases" but a lot of pretty straightforward stuff.
Take this file, say `mixins.less`
```less
.wrapper {
    color: #bbbbbb;
    display: block;
    font-size: 16px;
}

.link {
    color: #3E6992;
}
```
These two will render very different
```less
.my-block {
    a {
        .wrapper();
        .link();
    }
}

.my-other-block {
    a {
        .link();
        .wrapper();
    }
}
```

But i guess an option to validate mixin ordering that's disabled as default wouldn't hurt anyone :)

**Comment by shellscape** [comment]
@kokarn that's actually an anti-pattern (applying multiple mixins that assign the same property) for less :)  I called it an edge case only because the shops I've worked at had standardized on never doing that.

**Comment by kokarn** [comment]
Oh. Didn't actually know that. We use mixins for a bunch of stuff and have never thought about that :P

**Comment by shellscape** [comment]
Different strokes for different folks! :D

**Comment by shellscape** [comment]
After having used lesshint for some time now, I've reconsidered this. Closing!
