### ISSUE TITLE
nested @media queries erroneously trigger singleLinePerProperty rule

### ISSUE THREAD

**Issue by egid** [lesshint/lesshint#97]
The following...

```
section {
	@media (min-width: 300px) {
		font-size: inherit;
	}
}
```

... fires a warning for the `singleLinePerProperty` rule: "Each property should be on its own line."; the same rule, without the nested query, doesn't trigger any warnings:

```
@media (min-width: 300px) {
	section {
		font-size: inherit;
	}
}
```

Both are [valid Less](http://less2css.org/#%7B%22less%22%3A%22section%20%7B%5Cn%5Ct%40media%20(min-width%3A%20300px)%20%7B%5Cn%5Ct%5Ctfont-size%3A%20inherit%3B%5Cn%5Ct%7D%5Cn%7D%5Cn%5Cn%40media%20(min-width%3A%20300px)%20%7B%5Cn%5Ctsection%20%7B%5Cn%5Ct%5Ctfont-size%3A%20inherit%3B%5Cn%5Ct%7D%5Cn%7D%5Cn%22%7D).

**Comment by shellscape** [comment]
I can take a look at this for you tomorrow.

**Comment by jwilsson** [comment]
@shellscape You want me to take a look?

**Comment by shellscape** [comment]
@jwilsson sure man. apologies, it's been nuts on my end lately.

**Comment by jwilsson** [comment]
Sorry for the silence on this, I'll take a look tonight.

**Comment by shellscape** [comment]
:+1:

**Comment by egid** [comment]
🆒
